src/api.py
Provide API service for fine-tuned models.
=> Support conversation via API.

src/api_demo.py
=> Compatible with OpenAI API.

src/utils/common.py, src/utils/config.py, src/utils/configuration_baichuan.py, src/utils/modeling_baichuan.py
直接使用你的代码进行baichuan-7B训练。会报如下错误https://github.com/baichuan-inc/baichuan-7B/issues/23#issuecomment-1592658897：
> RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
这是因为 baichuan-7B 使用了 xformers 库来加速多头注意力计算，但这个库只支持计算卡，如 V100，A100，H100等，3090 不支持。https://github.com/facebookresearch/xformers/issues/628#issuecomment-1375591634：
> It looks like you are doing the right things.
Unfortunately, I don't have an RTX 3090 at hand to test, and this GPU is also not a priority for us, as we focus on V100/A100 mostly. If you can find a fix, we can get it landed, …
=> Support baichuan-7B training on RTX3090

src/utils/common.py
=> Fix typo in common.py

README.md, data/dataset_info.json
Update dataset_info.json and README.md
=> Support for WebNovel dataset

src/llmtuner/extras/template.py
=> [feature] Fix template of Llama2 to match the offical template

.gitignore
Add a.gitignore file to the project, which helps to exclude certain files and folders from being tracked by Git.
=> [Enhance] Add .gitignore file

data/README.md, data/README_zh.md
其实在代码里`src/llmtuner/tuner/rm/collator.py`已经说了，就是埋得太深，所以建议在README里说明一下。
=> add rm dataset explanation

src/llmtuner/webui/utils.py
support https://github.com/hiyouga/LLaMA-Efficient-Tuning/issues/673
=> add text format dataset preview in webui

README.md, README_zh.md, data/README.md, data/README_zh.md, data/dataset_info.json, src/llmtuner/extras/constants.py, src/llmtuner/hparams/data_args.py, src/llmtuner/webui/common.py, src/llmtuner/webui/components/train.py
1. add dataset stage variable
2. filter dataset automatically when choosing training stage in webui
=> add dataset stage

README.md, README_zh.md, src/llmtuner/hparams/finetuning_args.py, src/llmtuner/tuner/sft/trainer.py, src/llmtuner/tuner/sft/workflow.py
This pull request provides an implementation of NEFTune optimization, based on the paper: [NEFTune: Noisy Embeddings Improve Instruction Finetuning](https://arxiv.org/abs/2310.05914).
=> add NEFTune optimization

README.md, README_zh.md, src/llmtuner/hparams/finetuning_args.py, src/llmtuner/train/ppo/workflow.py
=> Change the default argument settings for PPO training

data/dataset_info.json
Added the Nectar dataset already preprocessed and divided in sft and rl to which I added a preprompt to each instruction since it has been seen that this increase instruction following
=> Update dataset_info.json - Added Nectar

README.md, README_zh.md, src/llmtuner/extras/constants.py, src/llmtuner/hparams/model_args.py, src/llmtuner/model/loader.py, src/llmtuner/webui/common.py
Support ModelScope hub in train/inference/webui/cli
=> Support ModelScope hub

requirements.txt
https://github.com/huggingface/transformers/pull/28078
=> Update transformers to 4.36.2 to resolve multi-node saving bug.

src/llmtuner/model/patcher.py
Related to issue https://github.com/hiyouga/LLaMA-Factory/issues/2315
Thanks.
=> Add patch_mixtral_replace_moe_impl for full training Mitral using DeepSpeed Zero3

src/llmtuner/data/template.py
when eos_token_id=0, it will never add eos_token
=> fix eos_token_id=0 bug

src/llmtuner/train/ppo/workflow.py
add project_kwargs param in PPOConfig，it can solve the issue [#1163](https://github.com/hiyouga/LLaMA-Factory/issues/1163)
=> update project_kwargs for ppo config

src/llmtuner/data/template.py, src/llmtuner/extras/constants.py
Hi，This PR mainly adds support for the Chinese Atom model， which could be found in [https://github.com/LlamaFamily/Llama-Chinese](https://github.com/LlamaFamily/Llama-Chinese).
hope to merge this PR, and then we will update the usage to the Llama2-Chinese repository to facilitate users in using Llama-Factory.
=> Support Atom Model

requirements.txt
=> bump accelerate

examples/extras/lora_plus/sft.sh, src/llmtuner/hparams/finetuning_args.py, src/llmtuner/train/sft/workflow.py, src/llmtuner/train/utils.py
Feature: add lora+ algorithm (see:https://arxiv.org/pdf/2402.12354.pdf)
we got result on spider experiment:
{
"rouge-1": 79.56683916827852,
"rouge-2": 63.493279206963244,
"rouge-l": 73.69117195357835,
"bleu-4": 72.11999584139265,
}
- [Y] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
=> [FEATURE]: ADD LORA+ ALGORITHM

README.md, README_zh.md
=> Update README.md, fix the release date of the paper

src/llmtuner/model/patcher.py, src/llmtuner/train/tuner.py
Fix Llama model save for full param train(also GaLore)
=> Fix Llama model save for full param train

src/llmtuner/extras/constants.py
=> support Qwen1.5-32B

src/llmtuner/model/adapter.py
=> Pass additional_target to unsloth

examples/README_zh.md, examples/full_multi_gpu/predict.sh
=> Added specimens for single-card full parameter prediction

src/llmtuner/webui/components/data.py
support for previewing custom dataset in directory format
=> support for previewing custom dataset in directory format

src/llmtuner/webui/chatter.py
=> add webui backend option

examples/extras/badam/sft.sh
Fix badam example argument.
Replaced `--badam_switch_block_every` with `--badam_switch_interval`
=> Fix badam example argument

README.md, README_zh.md
Add contribution to my tool/model Luminia-13B to generate prompt to create Stable diffusion Image.
=> Add contribution Luminia

data/dataset_info.json
Fixes https://github.com/hiyouga/LLaMA-Factory/issues/3650
=> fix sha1 of glaive_toolcall dataset

README.md, README_zh.md
Modify the RAEDME.md and README_zh.md file to add adapted to 910B image
=> added adapted to 910B image

src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
Add TeleChat-12B/TeleChat-12B-v2 models.
[TeleChat](https://github.com/Tele-AI/Telechat) is a large language model developed and trained by China Telecom Artificial Intelligence Technology Co., Ltd.
=> add TeleChat-12B/TeleChat-12B-v2 models

src/llamafactory/webui/runner.py
=> Fix cann't interrupt training when using multi GPUs in webui

src/llamafactory/extras/callbacks.py, src/llamafactory/webui/runner.py
add throughput (tokens/s) entry to log
=> add throughput entry to training log

README.md, README_zh.md
=> fix README

src/llamafactory/chat/vllm_engine.py
=> adapt vllm==0.5.0

.github/workflows/tests.yml, README.md, README_zh.md, examples/README.md, examples/README_zh.md, examples/extras/pissa/llama3_lora_sft.yaml, scripts/pissa_init.py, src/llamafactory/hparams/finetuning_args.py, src/llamafactory/hparams/model_args.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/adapter.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/pt/trainer.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/train/trainer_utils.py, src/llamafactory/webui/components/train.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py, tests/model/test_base.py, tests/model/test_lora.py, tests/model/test_pissa.py
Fix #3162 
Fix #3196 
Fix #3778
=> Support pissa

.github/workflows/label_issue.yml
Auto-label  NPU issue by detecting keywards like `npu`, `ascend`, `昇腾`
=> auto-label npu issue

docker/docker-cuda/docker-compose.yml, docker/docker-npu/docker-compose.yml
=> fix docker-compose path

src/llamafactory/cli.py
Associate the exit status of the parent process with that of its subprocesses.
=> Exit the process with the subprocess's return code when utilizing the CLI

src/llamafactory/train/sft/trainer.py
=> Fix bug when using pissa method with deepspeed

src/llamafactory/extras/constants.py
Add [Tele-AI/TeleChat-1B](https://huggingface.co/Tele-AI/TeleChat-1B)
=> Add TeleChat-1B

README.md, README_zh.md
add [LazyLLM](https://github.com/LazyAGI/LazyLLM) to `Projects using LLaMA Factory` in `README.md`
LazyLLM  is a low-code development tool for building multi-agent LLMs(large language models) applications. It assists developers in creating complex AI applications at very low costs and enables continuous iterative optimization. LazyLLM offers a convenient workflow for application building and provides numerous standard processes and tools for various stages of the application development process.
We will use LLaMaFactory to support sft:  https://github.com/LazyAGI/LazyLLM/pull/51/files
=> Add `LazyLLM` to `Projects using LLaMA Factory` in `README.md`

docker/docker-cuda/Dockerfile, src/llamafactory/train/callbacks.py
=> Fix cuda Dockerfile

tests/data/test_template.py
add github action check to ignore some test cases
=> add github action check to ignore some test cases

README.md, README_zh.md
=> Added the reference address for TRL PPO details.

src/llamafactory/data/template.py
Update chat template for deepseek: add format_system field
=> update deepseek template

src/llamafactory/train/callbacks.py
fix pissa train callback, https://github.com/hiyouga/LLaMA-Factory/issues/4992
=> fix pissa callback

README.md, README_zh.md
- [1] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [1 ] Did you write any new necessary tests?
=> 增加了MiniCPM在页面首页的支持列表，MiniCPM官方github也放了LLama_factory的友情链接

src/llamafactory/extras/constants.py
Fixes https://github.com/hiyouga/LLaMA-Factory/issues/5035
=> support gemma-2-2b

examples/train_full/llama3_full_predict.yaml
Fixes https://github.com/hiyouga/LLaMA-Factory/issues/5092
=> fix eval_dataset in example

src/llamafactory/train/ppo/trainer.py
Fixes #5060 (issue)
The optimizer with lr_scheduler was not added to trainer.
=> fix lr not change

src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> 增加了对minicpm3.0的适配'

src/llamafactory/model/model_utils/liger_kernel.py
Add qwen_vl to liger kernel supported list
=> Add qwen_vl to liger kernel supported list

README.md, README_zh.md, src/llamafactory/extras/constants.py
=> Chore: Support llama3.2.

README.md, README_zh.md, data/dataset_info.json, src/llamafactory/__init__.py, src/llamafactory/data/loader.py, src/llamafactory/data/parser.py, src/llamafactory/extras/constants.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/model_args.py, src/llamafactory/model/loader.py, src/llamafactory/webui/common.py
add [modelers hub](https://modelers.cn/) support
- [√ ] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [√] Did you write any new necessary tests?
=> [hub support] add modelers hub support

setup.py, src/llamafactory/hparams/parser.py
vllm 0.6.3.dev is from main. Also add support Jetson from Nvidia
https://github.com/dusty-nv/jetson-containers/pull/670
=> vllm 0.6.3

README.md, README_zh.md
- [ 1 ] Did you read the [[contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [1 ] Did you write any new necessary tests?
对于LLM做reranker任务：在实验中使用了LLaMA-Factory作为Reranker任务的微调框架，后续RAG-Retrieval支持将训练好的生LLM，蒸馏到BERT中。
实验报告：https://zhuanlan.zhihu.com/p/987727357
蒸馏到BERT中的代码：https://github.com/NLPJCL/RAG-Retrieval/tree/master/examples/distill_llm_to_bert
=> 使用了 LLaMA Factory 的项目：RAG-Retrieval 使用LLaMA-Factory作为生成方法做Reranker任务的微调框架。

requirements.txt, src/llamafactory/__init__.py, src/llamafactory/data/loader.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/misc.py, src/llamafactory/extras/packages.py, src/llamafactory/model/model_utils/longlora.py, src/llamafactory/model/model_utils/packing.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py, src/llamafactory/train/ppo/trainer.py, src/llamafactory/train/pt/trainer.py, src/llamafactory/train/rm/trainer.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/webui/components/top.py, src/llamafactory/webui/components/train.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py
=> [loss&ui] fix incorrect loss of vlms, add extra args to ui

README.md, README_zh.md
=> [misc] update readme

.github/CONTRIBUTING.md, .pre-commit-config.yaml, README.md, README_zh.md, scripts/test_image.py, src/llamafactory/api/chat.py, src/llamafactory/chat/base_engine.py, src/llamafactory/chat/chat_model.py, src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/webui/chatter.py
- Support inputing multiple images at inference
=> [inference] support multiple images

src/llamafactory/data/template.py, src/llamafactory/model/loader.py
=> [data] fix template replace behavior

src/llamafactory/data/aligner.py, src/llamafactory/hparams/data_args.py
=> [data] support auto convert for single image, add image_dir argument

src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/data/mm_plugin.py
=> [fix] chat engines

src/llamafactory/chat/vllm_engine.py
=> [generation] fix vllm v0.6.3

src/llamafactory/webui/runner.py
=> [webui] fix extra args

src/llamafactory/chat/vllm_engine.py
=> [generate] fix vllm config args

src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> [model] add qwen-coder and opencoder

requirements.txt
=> [misc] fix dep package version

README.md, README_zh.md
=> [readme] update readme

src/llamafactory/chat/vllm_engine.py
=> [inference] fix qwen2vl vllm infer

src/llamafactory/cli.py
=> [cli] remove shell=True in cli

src/llamafactory/extras/env.py
=> [release] release v0.9.1

src/llamafactory/extras/env.py
=> [misc] set dev version

src/llamafactory/model/model_utils/visual.py
=> [model] fix mllama hidden_size

data/dataset_info.json
=> [data] update dataset info

src/llamafactory/data/mm_plugin.py
=> [data] fix mllama plugin

src/llamafactory/data/mm_plugin.py
=> [misc] chore: lint

src/llamafactory/data/collator.py, src/llamafactory/data/mm_plugin.py
=> [model] fix mllama cross mask

src/llamafactory/data/collator.py, tests/data/test_collator.py, tests/data/test_mm_plugin.py
We add dummy image features at the end of sequence to avoid hanging of VLM training in zero3/fsdp mode.
Fixes #5714
=> [data] fix vlm zero3 training

src/llamafactory/webui/interface.py
As the title suggest, show the hostname in the webui title to avoid being confused when multiple llama factory instances are running.
=> [+] Show the hostname in webui title

scripts/async_call_api.py, scripts/vllm_infer.py
Provides a script for batch inference using vLLM.
=> add vllm_infer script

scripts/stat_utils/cal_lr.py, scripts/stat_utils/cal_ppl.py, scripts/stat_utils/length_cdf.py, src/llamafactory/data/collator.py
=> [script] fix scripts

scripts/stat_utils/cal_lr.py, scripts/vllm_infer.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/data/mm_plugin.py
=> [infer] support qwen2vl vllm infer

examples/train_full/qwen2vl_full_sft.yaml, src/llamafactory/model/model_utils/visual.py
=> [model] support qwen2vl train proj only

examples/README.md, examples/README_zh.md
=> [examples] fix multinode examples

src/llamafactory/data/collator.py, src/llamafactory/train/dpo/workflow.py, src/llamafactory/train/kto/workflow.py, src/llamafactory/train/ppo/workflow.py, src/llamafactory/train/pt/trainer.py, src/llamafactory/train/rm/trainer.py, src/llamafactory/train/rm/workflow.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/train/sft/workflow.py
=> [model] fix: qwen2vl mrope

src/llamafactory/__init__.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/packing.py, src/llamafactory/model/patcher.py
=> [model] generalized packing

src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/hparams/generating_args.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/train/sft/workflow.py
=> [infer] support control eos

src/llamafactory/hparams/model_args.py, src/llamafactory/model/model_utils/checkpointing.py
=> [model] support non-reenterent-gc

src/llamafactory/data/formatter.py, src/llamafactory/data/template.py, src/llamafactory/data/tool_utils.py, src/llamafactory/extras/constants.py, tests/data/test_formatter.py
=> [model&template] add llama3.3 & support llama3 tool prompt

src/llamafactory/data/template.py, src/llamafactory/data/tool_utils.py, tests/data/test_formatter.py
=> [template] support qwen2 tool template

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> support telechat2 model

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/webui/locales.py
=> [model] add paligemma2

src/llamafactory/webui/chatter.py, src/llamafactory/webui/components/export.py
=> [webui] fix webui args

.gitignore, src/llamafactory/hparams/generating_args.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/train/sft/workflow.py, tests/e2e/test_train.py, tests/train/test_sft_trainer.py
=> [generate] fix generate kwargs

README.md, README_zh.md
👋Add a section in the README to introduce how to use SwanLab.
=> docs: use swanlab

README.md, README_zh.md, src/llamafactory/extras/constants.py
=> [modle] add qvq

src/llamafactory/cli.py, src/llamafactory/data/collator.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py, src/llamafactory/train/pt/trainer.py, src/llamafactory/train/rm/trainer.py, src/llamafactory/train/sft/trainer.py
Fixes #6448 and fix paligemma collator
=> [trainer] fix eval loss

setup.py, src/llamafactory/chat/hf_engine.py, src/llamafactory/data/collator.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/parser.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py
=> [model] update vllm & fix paligemma dtype

src/llamafactory/data/template.py
Fix #5506 
- [-] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [-] Did you write any new necessary tests?
=> Add deepseek-v2.5 template

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> [model] add deepseek3 model

src/llamafactory/data/preprocess.py, src/llamafactory/data/processors/pretrain.py, src/llamafactory/data/processors/unsupervised.py, src/llamafactory/train/sft/trainer.py, src/llamafactory/train/sft/workflow.py
=> [trainer] fix generate logic

scripts/llama_pro.py, scripts/stat_utils/cal_lr.py, scripts/stat_utils/cal_ppl.py, scripts/stat_utils/length_cdf.py, scripts/vllm_infer.py
=> [misc] update scripts

src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py, src/llamafactory/train/trainer_utils.py
=> [trainer] fix pixtral dpo

src/llamafactory/chat/hf_engine.py, src/llamafactory/data/data_utils.py, src/llamafactory/data/loader.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/logging.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/model_utils/attention.py, src/llamafactory/model/model_utils/checkpointing.py, src/llamafactory/model/model_utils/longlora.py, src/llamafactory/model/model_utils/moe.py, src/llamafactory/model/model_utils/packing.py, src/llamafactory/model/model_utils/quantization.py, src/llamafactory/train/callbacks.py, src/llamafactory/train/sft/workflow.py
=> [misc] imporve log

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, tests/data/test_template.py
- Add Phi-4 model by microsoft
- Remove `format_separator` in template to avoid misunderstanding
=> [model] add phi4 model

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature-request.yml, .github/workflows/label_issue.yml
=> [gh] update issue template

examples/train_full/qwen2vl_full_sft.yaml, setup.py, src/llamafactory/data/template.py, src/llamafactory/hparams/finetuning_args.py, src/llamafactory/model/loader.py, src/llamafactory/model/model_utils/misc.py, src/llamafactory/model/model_utils/visual.py, tests/data/test_template.py, tests/model/model_utils/test_checkpointing.py, tests/model/model_utils/test_visual.py
=> [model] refactor mllm param logic

src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py
=> [model] fix mllama any image

README.md, src/llamafactory/chat/hf_engine.py, src/llamafactory/data/template.py, src/llamafactory/model/loader.py, src/llamafactory/model/patcher.py
=> [misc] lint

README.md, README_zh.md, examples/README.md, examples/README_zh.md, examples/extras/apollo/llama3_full_sft.yaml, examples/extras/galore/llama3_full_sft.yaml, src/llamafactory/extras/packages.py, src/llamafactory/hparams/finetuning_args.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/model_utils/misc.py, src/llamafactory/train/trainer_utils.py, src/llamafactory/webui/components/train.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py
=> [optim] clean apollo

README.md, README_zh.md
=> [assets] update readme

src/llamafactory/hparams/data_args.py, src/llamafactory/webui/locales.py
Update English description of `val_size` in `data_args.py` and `locales.py`.
=> Update `val_size` english description 

src/llamafactory/model/model_utils/moe.py
=> [model] fix qwen2 moe

requirements.txt, src/llamafactory/webui/chatter.py, src/llamafactory/webui/components/chatbot.py, src/llamafactory/webui/components/top.py, src/llamafactory/webui/components/train.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py, src/llamafactory/webui/utils.py
=> [webui] upgrade gradio v5

examples/extras/adam_mini/qwen2_full_sft.yaml, examples/extras/apollo/llama3_full_sft.yaml, examples/extras/badam/llama3_full_sft.yaml, examples/extras/fsdp_qlora/llama3_lora_sft.yaml, examples/extras/galore/llama3_full_sft.yaml, examples/extras/llama_pro/llama3_freeze_sft.yaml, examples/extras/loraplus/llama3_lora_sft.yaml, examples/extras/mod/llama3_full_sft.yaml, examples/extras/pissa/llama3_lora_sft.yaml, examples/train_full/llama3_full_sft.yaml, examples/train_full/qwen2vl_full_sft.yaml, examples/train_lora/llama3_lora_dpo.yaml, examples/train_lora/llama3_lora_kto.yaml, examples/train_lora/llama3_lora_ppo.yaml, examples/train_lora/llama3_lora_pretrain.yaml, examples/train_lora/llama3_lora_reward.yaml, examples/train_lora/llama3_lora_sft.yaml, examples/train_lora/llama3_lora_sft_ds3.yaml, examples/train_lora/llama3_lora_sft_ray.yaml, examples/train_lora/llama3_preprocess.yaml, examples/train_lora/llava1_5_lora_sft.yaml, examples/train_lora/qwen2vl_lora_dpo.yaml, examples/train_lora/qwen2vl_lora_sft.yaml, examples/train_qlora/llama3_lora_sft_aqlm.yaml, examples/train_qlora/llama3_lora_sft_awq.yaml, examples/train_qlora/llama3_lora_sft_bnb_npu.yaml, examples/train_qlora/llama3_lora_sft_gptq.yaml, examples/train_qlora/llama3_lora_sft_otfq.yaml, requirements.txt, src/llamafactory/hparams/finetuning_args.py
=> [examples] disable val set by default

src/llamafactory/data/mm_plugin.py
=> [misc] update mm plugin

src/llamafactory/webui/components/top.py, src/llamafactory/webui/interface.py, src/llamafactory/webui/locales.py
Only add support for japanese language, no others。
For example:
- [Yes] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [No] Did you write any new necessary tests?
=> Add support for japanese language

README.md, README_zh.md, src/llamafactory/extras/constants.py, src/llamafactory/webui/chatter.py
Add DeepSeek R1 for LLaMA-Factory
* Qwen-1.5B 7B 14B 32B
* Llama-8B 70B
* DeepSeek-R1 671B
* DeepSeek-R1-Zero 671B
=> Add DeepSeek-R1 and its distilled model (Qwen&Llama)

README.md, README_zh.md, src/llamafactory/chat/hf_engine.py, src/llamafactory/data/collator.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/extras/constants.py, src/llamafactory/hparams/model_args.py, src/llamafactory/model/model_utils/visual.py
=> [model] add qwen2.5 vl models

.github/workflows/publish.yml, .github/workflows/tests.yml
=> [misc] update workflows

src/llamafactory/data/mm_plugin.py, src/llamafactory/extras/constants.py
=> [data] fix qwen2vl plugin

requirements.txt, setup.py, src/llamafactory/__init__.py, src/llamafactory/cli.py, src/llamafactory/extras/env.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/model_utils/packing.py, src/llamafactory/model/patcher.py, src/llamafactory/train/callbacks.py, src/llamafactory/webui/interface.py, src/webui.py
=> [deps] upgrade vllm

README.md, README_zh.md, data/dataset_info.json, src/llamafactory/data/template.py, src/llamafactory/webui/chatter.py
=> [dataset] add openthought dataset

src/llamafactory/data/formatter.py, src/llamafactory/data/tool_utils.py, tests/data/test_formatter.py
=> [test] align test cases

src/llamafactory/data/collator.py
=> [data] fix mllama collator

src/llamafactory/data/aligner.py
=> fix-sharegpt-format

src/llamafactory/data/mm_plugin.py
=> [data] refactor mm plugin

scripts/export_ollama_modelfile.py, scripts/test_ollama_modelfile.py
support ollama modelfile export and add some test cases
=> support ollama modelfile export

src/llamafactory/data/template.py, src/llamafactory/webui/control.py, tests/data/test_template.py
=> [data] refactor template

src/llamafactory/data/template.py, src/llamafactory/hparams/parser.py, tests/data/test_template.py
=> [data] feat: auto template

src/llamafactory/data/collator.py, src/llamafactory/train/kto/trainer.py
=> Fix llama3.2 vision kto train

examples/README.md
Fixes typo in USE_RAY=1 example in examples!
=> fix path to ray example

README.md, README_zh.md
=> [misc] update readme 

src/llamafactory/model/model_utils/liger_kernel.py
=> [model] add liger kernel to qwen2_5 vl

src/llamafactory/data/mm_plugin.py, src/llamafactory/extras/constants.py, src/llamafactory/model/adapter.py, src/llamafactory/model/model_utils/misc.py, src/llamafactory/model/model_utils/visual.py
=> [misc] fix lora regex

src/llamafactory/data/template.py
=> [template] fix system_prompt of minicpm_v/minicpm_o

src/llamafactory/data/loader.py
=> [data] fix predict dataset

scripts/vllm_infer.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/data/mm_plugin.py
=> [misc] fix script

src/llamafactory/webui/components/chatbot.py, src/llamafactory/webui/css.py
=> [misc] update css

examples/train_full/llama3_full_sft.yaml, examples/train_lora/llama3_lora_dpo.yaml, examples/train_lora/llama3_lora_pretrain.yaml, examples/train_lora/llama3_lora_reward.yaml, examples/train_lora/llama3_lora_sft.yaml, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> [model] add models

src/llamafactory/data/mm_plugin.py, tests/data/test_mm_plugin.py
=> [data] fix mllama

src/llamafactory/extras/constants.py
=> add paligemma2-mix series

scripts/vllm_infer.py
Ensure vLLM inference results vary across runs.
=> add seed args

src/llamafactory/data/mm_plugin.py
=> [data] use bicubic resampler

examples/train_full/llama3_full_sft.yaml, examples/train_full/qwen2vl_full_sft.yaml, examples/train_lora/llama3_lora_dpo.yaml, examples/train_lora/llama3_lora_pretrain.yaml, examples/train_lora/llama3_lora_reward.yaml, examples/train_lora/llama3_lora_sft.yaml, examples/train_lora/llama3_lora_sft_ds3.yaml, examples/train_lora/llama3_lora_sft_ray.yaml, examples/train_lora/llava1_5_lora_sft.yaml, examples/train_lora/qwen2vl_lora_dpo.yaml, examples/train_lora/qwen2vl_lora_sft.yaml, src/llamafactory/data/mm_plugin.py, src/llamafactory/train/tuner.py
=> [trainer] update config

src/llamafactory/train/trainer_utils.py
=> fix: swanlab version

src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py
=> [data] fix mm template

scripts/vllm_infer.py
=> [script] fix vllm version

src/llamafactory/cli.py, src/llamafactory/hparams/finetuning_args.py, src/llamafactory/hparams/model_args.py, src/llamafactory/hparams/parser.py, src/llamafactory/train/tuner.py
=> [misc] fix cli

examples/accelerate/fsdp_config.yaml, examples/deepspeed/ds_z0_config.json, examples/deepspeed/ds_z2_config.json, examples/deepspeed/ds_z2_offload_config.json, examples/deepspeed/ds_z3_config.json, examples/deepspeed/ds_z3_offload_config.json
=> [misc] fix ds config

src/llamafactory/data/data_utils.py, src/llamafactory/data/loader.py, src/llamafactory/train/test_utils.py, tests/data/processor/test_feedback.py, tests/data/processor/test_pairwise.py, tests/data/processor/test_supervised.py, tests/data/processor/test_unsupervised.py, tests/data/test_converter.py, tests/data/test_loader.py, tests/e2e/test_train.py, tests/model/model_utils/test_checkpointing.py, tests/model/test_freeze.py, tests/model/test_full.py, tests/model/test_lora.py, tests/model/test_pissa.py, tests/train/test_sft_trainer.py
=> [data] fix loader

src/llamafactory/hparams/parser.py
=> [config] fix export max len

README.md, README_zh.md, examples/train_full/qwen2vl_full_sft.yaml, setup.py, src/llamafactory/api/app.py, src/llamafactory/chat/base_engine.py, src/llamafactory/chat/chat_model.py, src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/extras/constants.py, src/llamafactory/hparams/finetuning_args.py, src/llamafactory/hparams/model_args.py, src/llamafactory/model/model_utils/attention.py, src/llamafactory/model/model_utils/rope.py, src/llamafactory/model/model_utils/visual.py, tests/model/model_utils/test_visual.py
=> [config] update args

README.md, README_zh.md, scripts/vllm_infer.py, src/llamafactory/chat/vllm_engine.py
=> [infer] fix vllm args

src/llamafactory/data/loader.py
=> [data] avoid exit after saving preprocessed data

src/llamafactory/extras/env.py
=> [misc] support print commit info

requirements.txt, src/llamafactory/extras/env.py, src/llamafactory/train/tuner.py
=> [release] release v0.9.2

.github/workflows/publish.yml, .github/workflows/tests.yml
=> [ci] update workflow

requirements.txt, src/llamafactory/__init__.py, src/llamafactory/extras/misc.py
=> [misc] upgrade deps

README.md, README_zh.md, pyproject.toml, src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/loader.py, src/llamafactory/model/model_utils/visual.py, src/llamafactory/model/patcher.py
=> [model] support gemma3

README.md
=> [assets] update video

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
Support **[Tencent-Hunyuan-7B](https://huggingface.co/tencent/Hunyuan-7B-Instruct)** model.
Fixes #6919
Create a new file `examples/train_lora/huanyuan_7b_sft.yaml` with the following content:
```yaml
model_name_or_path: tencent/Hunyuan-7B-Instruct
trust_remote_code: true
stage: sft
do_train: true
lora_rank: 8
dataset: identity,alpaca_en_demo
template: hunyuan
preprocessing_num_workers: 16
dataloader_num_workers: 4
overwrite_output_dir: true
save_only_model: false
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000 …
```
=> [Model]supported tencent-hunyuan model(fixed#7312)

README.md, README_zh.md
=> [assets] update videos

setup.py
=> [version] fix minicpmo

src/llamafactory/train/tuner.py
=> [bug] fix redundant process group destroy for ray

setup.py, src/llamafactory/cli.py, src/llamafactory/hparams/parser.py, src/llamafactory/webui/chatter.py
=> [deps] upgrade vllm to 0.8

requirements.txt, src/llamafactory/__init__.py, src/llamafactory/data/parser.py, src/llamafactory/extras/misc.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py
=> [deps] upgrade transformers to 4.50.0

scripts/eval_bleu_rouge.py
=> [misc] fix license

src/llamafactory/data/mm_plugin.py, src/llamafactory/train/dpo/trainer.py, src/llamafactory/train/kto/trainer.py, src/llamafactory/train/pt/trainer.py, src/llamafactory/train/sft/trainer.py
=> [trainer] fix vlm loss for transformers 4.49

README.md, README_zh.md
=> [assets] fix gemma3 readme

src/llamafactory/model/model_utils/liger_kernel.py
Enable Liger-Kernel for Gemma-3 Text and Paligemma to extend the work on #7462.
=> add gemma3 text and paligemma

setup.py, src/llamafactory/model/model_utils/liger_kernel.py
=> Update liger-kernel's monkey patch

src/llamafactory/hparams/finetuning_args.py, src/llamafactory/train/trainer_utils.py
=> [3rdparty] support swanlab lark(飞书) notification

requirements.txt
=> [deps] pin pydantic to 2.10.6

src/llamafactory/data/collator.py
=> [data] fix qwen2.5 omni collator

setup.py
Supports inference for new models like `llama4`, `gemma3`, etc. with `sglang`
=> [Feature] sglang supports transformers==4.51.0

.github/workflows/publish.yml, .github/workflows/tests.yml, Makefile, pyproject.toml, setup.py
=> [deps] fix uv conflicts

requirements.txt, src/llamafactory/cli.py, src/llamafactory/extras/constants.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/patcher.py, src/llamafactory/webui/runner.py
| TORCH_NCCL_AVOID_RECORD_STREAMS | DeepSpeed | VRAM |
| ---- | ---- | ---- |
| 1 | Off | 18.3GB |
| 0 | Off | 29.8GB |
| 1 | On | 18.2GB |
| 0 | On | 18.9GB |
=> [misc] upgrade cli

src/llamafactory/api/chat.py
=> [api] fix chat messages

examples/README.md, examples/README_zh.md, src/llamafactory/cli.py
Support inference with vLLM-Ascend
Fixes #7447 
For applications that start vLLM GPU and NPU programs in subprocess mode, you need to use spawn to pull the subprocess. For such application code, you need to use freeze_support to protect recursive imports and pull subprocesses. Other information can see in [url](https://docs.vllm.ai/en/v0.7.3/design/multiprocessing.html).
- [*] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [*] Did you write any new necessary tests?
I verified with two NPU cards, it okay, as following:
=> Support inference with vLLM-Ascend

examples/README.md, examples/README_zh.md, src/llamafactory/cli.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/patcher.py
=> [infer] set env for vllm ascend

README.md, README_zh.md, examples/README.md, examples/README_zh.md, examples/train_lora/llama3_lora_sft.sh, src/llamafactory/hparams/model_args.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/model_utils/quantization.py, src/llamafactory/model/patcher.py, src/llamafactory/third_party/muon/muon.py, src/llamafactory/train/trainer_utils.py, tests/model/model_utils/test_add_tokens.py
=> [example] add bash usage

src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/model/loader.py
=> [data] improve mmplugin

src/llamafactory/hparams/finetuning_args.py, src/llamafactory/train/tuner.py
=> [trainer] support early stop

src/llamafactory/data/mm_plugin.py, src/llamafactory/extras/constants.py, tests/data/test_mm_plugin.py
Align with the latest Transformers code instead of self-hosted one.
=> [misc] update internvl constants

src/llamafactory/model/model_utils/moe.py
=> [model] fix moe zero3

src/llamafactory/model/model_utils/checkpointing.py
=> [model] fix vit gradient checkpointing

src/llamafactory/data/mm_plugin.py
=> [data] fix minicpmo vllm infer

src/llamafactory/model/adapter.py
when using freeze training with freeze_multi_modal_projector=False, the multi_modal_projector is freeze
=> the bug between freeze training and freeze_multi_modal_projector

src/llamafactory/data/mm_plugin.py
=> [data] fix qwen2 omni plugin

src/llamafactory/data/mm_plugin.py, src/llamafactory/model/model_utils/moe.py
=> [model] fix dsv3 leaf node

src/llamafactory/data/mm_plugin.py, tests/data/test_mm_plugin.py, tests/version.txt
1. lint plugin
2. Add test for qwen_omni plugin
3. Fix the replacement issue and support the mixed dataset training when `use_audio_in_video=True`
=> [data] Qwen_omini template fix

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/webui/control.py, tests/data/test_template.py, tests/version.txt
=> [model] add qwen3

src/llamafactory/data/mm_plugin.py
=> [data] improve mm plugin

src/llamafactory/data/template.py
=> [data] replace eos token for base models

src/llamafactory/data/loader.py, src/llamafactory/hparams/data_args.py, src/llamafactory/hparams/training_args.py
=> [data] add eval_on_each_dataset arg

README.md, README_zh.md, src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/sglang_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/webui/chatter.py, src/llamafactory/webui/components/chatbot.py, src/llamafactory/webui/locales.py, tests/data/test_template.py
=> [data] optimize qwen3 loss computation

src/llamafactory/data/mm_plugin.py
=> [data] fix base plugin

src/llamafactory/chat/hf_engine.py, src/llamafactory/chat/sglang_engine.py, src/llamafactory/chat/vllm_engine.py, src/llamafactory/hparams/generating_args.py
=> [hparam] add enable think argument

src/llamafactory/model/model_utils/liger_kernel.py
=> [misc] update liger kernel patch

README.md, README_zh.md
This PR adds introduction link for GraphGen, a synthetic data generation tool.
- Github https://github.com/open-sciencelab/GraphGen
- Web https://g-app-center-000704-6802-aerppvq.openxlab.space/
- Paper https://github.com/open-sciencelab/GraphGen/blob/main/resources/GraphGen.pdf  (peer-review passed)
=> [docs] add GraphGen

src/llamafactory/data/mm_plugin.py
=> [data] fix kimi vl template

README.md, README_zh.md
=> [assets] update windows installation

src/llamafactory/data/data_utils.py
=> Add support for loading multiple files from remote

src/llamafactory/data/mm_plugin.py
=> [data] add forward compatibility for video_utils in Transformers 4.52.0

src/llamafactory/chat/sglang_engine.py, src/llamafactory/hparams/model_args.py, tests/e2e/test_sglang.py
=> fix: add loading lora using SGLang as infer_backend

requirements.txt, setup.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/model_utils/attention.py, src/llamafactory/model/model_utils/moe.py, src/llamafactory/model/model_utils/quantization.py, src/llamafactory/model/model_utils/rope.py, src/llamafactory/model/patcher.py
=> [model] switch to gptqmodel

src/llamafactory/api/chat.py, src/llamafactory/api/protocol.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> [model] add smollm2 and medgemma

src/llamafactory/webui/runner.py
=> [webui] fix input args

src/llamafactory/webui/chatter.py, src/llamafactory/webui/components/infer.py
=> [webui] add infer extra args

src/llamafactory/data/loader.py, src/llamafactory/hparams/data_args.py
=> [data] fix shared file system

src/llamafactory/data/data_utils.py, src/llamafactory/webui/common.py
=> [webui] fix skip args

src/llamafactory/extras/constants.py
=> [model] add deepseek 0528 models

src/llamafactory/model/loader.py, src/llamafactory/model/model_utils/unsloth.py
Fixes #8324 
- [YES] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [NO] Did you write any new necessary tests?
No new tests were required. However, I did test full fine-tuning with unsloth and it works as expected.
=> Pushing FFT with unsloth

src/llamafactory/model/patcher.py
=> [model] fix model generate

src/llamafactory/data/collator.py, src/llamafactory/extras/constants.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/loader.py, src/llamafactory/model/model_utils/visual.py, tests/data/test_collator.py, tests/version.txt
=> [data] fix qwen2vl pos ids

README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/unsloth.py
=> [model] add kimi vl 2506

src/llamafactory/extras/constants.py
=> [model] Add mistral-small 3.2 & kimi-dev

.github/workflows/tests.yml
=> [misc] fix ci

requirements.txt, src/llamafactory/extras/misc.py, src/llamafactory/model/loader.py
Fixes #8450 
Fixes #8451
Fixes #8454
=> [model] do not force load processor

src/llamafactory/api/chat.py, src/llamafactory/extras/logging.py, src/llamafactory/extras/misc.py, src/llamafactory/webui/components/__init__.py, src/llamafactory/webui/components/footer.py, src/llamafactory/webui/control.py, src/llamafactory/webui/interface.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py
Add stderr and vram monitor to llamaboard
=> [webui] upgrade webui and fix api

src/llamafactory/data/collator.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/visual.py
Add a new reasoning VLM glm4.1v
NOTE: GLM4.1V is not ready for video sft for now until this [PR](https://github.com/huggingface/transformers/pull/39090) is merged.
=> [model] add GLM-4.1V

src/llamafactory/data/collator.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/visual.py, src/llamafactory/model/patcher.py
Fixes #8486
NOTE: The hybrid cache setting in the generation configuration may raise issues.
=> [model] add gemma3n

.github/ISSUE_TEMPLATE/config.yml
=> [assets] update issue template

src/llamafactory/hparams/parser.py
=> fix: report to swanlab

.github/workflows/tests.yml, README.md, README_zh.md, docker/docker-cuda/README.md, requirements.txt, setup.py, src/llamafactory/data/mm_plugin.py, src/llamafactory/extras/misc.py, src/llamafactory/hparams/parser.py, src/llamafactory/model/loader.py, tests/data/test_mm_plugin.py
=> [deps] bump transformers to 4.49.0

requirements.txt, src/llamafactory/data/loader.py, src/llamafactory/extras/misc.py, src/llamafactory/webui/common.py, src/llamafactory/webui/components/top.py, src/llamafactory/webui/control.py, src/llamafactory/webui/engine.py, src/llamafactory/webui/interface.py, src/llamafactory/webui/locales.py
=> [webui] support other hub

src/llamafactory/extras/misc.py, src/llamafactory/webui/locales.py, src/llamafactory/webui/runner.py
Fix webui abort finish info
Add weak file lock on modelscope snapshot download
=> [webui] fix abort finish

src/llamafactory/data/mm_plugin.py
Make the video token replacement consistent. 
Should wait for the update of the upstream code.
=> [data] support glm4.1v video training

src/llamafactory/extras/constants.py
It is finetuned from [Mistral-Small-3.1](https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Base-2503), therefore IMO we can reuse `mistral_small` template.
=> [model] add Devstral-Small-2507

src/llamafactory/data/mm_plugin.py
Sorry for submitting a broken PR, now make up for the replacement issue. 😭
=> [data] fix gemma3n mmplugin

README.md, README_zh.md, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
=> [model] support granite4

src/llamafactory/extras/constants.py
=> [model] add qwen3 2507 models

src/llamafactory/data/template.py, src/llamafactory/extras/constants.py
Rename THUDM to zai-org & update constants of glm4.5
=> [model] update glm4.5

src/llamafactory/data/collator.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/visual.py
=> [model] support keye-vl-8b

setup.py, src/llamafactory/hparams/parser.py
=> [deps] upgrade vllm to 0.10.0

src/llamafactory/extras/constants.py
=> [model] Qwen3-30B-A3B-Thinking-2507

src/llamafactory/extras/constants.py
=> [model] add qwen3-4b-i/t

src/llamafactory/data/template.py
@BUAADreamer 
Follow [this snippet code](https://huggingface.co/openbmb/MiniCPM-o-2_6/blob/main/modeling_minicpmo.py#L683-L768)
Fixes #8901
=> [data] Fix MiniCPMO default system prompt

src/llamafactory/model/model_utils/liger_kernel.py
Fixes #8977
Use it with `pip install liger-kernel-nightly`
=> [misc] update glm4v ligerkernel

src/llamafactory/model/model_utils/visual.py
=> [model] add kimi_vl `_register_composite_model`

src/llamafactory/extras/constants.py
I’m bringing MiniCPM-V 4.5 in this PR.
Compared to the recently released MiniCPM-V 4.0, this new version puts more emphasis on performance metrics.
=> [model] Support MiniCPM-V 4.5

src/llamafactory/data/converter.py, src/llamafactory/data/template.py, src/llamafactory/data/tool_utils.py
Add bailing template v2 and a new DatasetConverter for the data format of OpenAI with function call
=> Bailing template v2

.github/workflows/tests.yml, requirements.txt, src/llamafactory/extras/misc.py, src/llamafactory/extras/packages.py, src/llamafactory/train/sft/metric.py
=> [deps] upgrade transformers to 4.56.1

src/llamafactory/data/mm_plugin.py, src/llamafactory/data/template.py, src/llamafactory/extras/constants.py, src/llamafactory/model/model_utils/visual.py
Fixes #8844
Fixes #8954
We need to modify the preprocessor config to make dots.ocr compatible with LlamaFactory:
```json
{
"min_pixels": 3136,
"max_pixels": 11289600,
"patch_size": 14,
"temporal_patch_size": 1,
"merge_size": 2,
"image_mean": [
0.48145466,
0.4578275,
0.40821073
],
"image_std": [
0.26862954,
0.26130258,
0.27577711
],
"image_processor_type": "Qwen2VLImageProcessor",
"processor_class": "Qwen2VLProcessor"
}
```
https://huggingface.co/rednote-hilab/dots.ocr/blob/main/preprocessor_config.json
=> [model] add dots ocr

README.md, README_zh.md
update ling-v2 to READNE&READNE_ZH
=> [docs] update ling-v2 to the readme

src/llamafactory/chat/chat_model.py, src/llamafactory/cli.py
1. 将cli下的各api进行依赖解耦，通过懒加载避免在一开始就将所有依赖的模块导入。例如，在用户只希望运行train时，不需要再强制要求导入或安装vllm等与train无关的依赖，其他api也类似。
2. 针对chat_model的不同backend，在使用到具体的backend的时候才进行相关模块导入。
=> Refactoring cli

src/llamafactory/cli.py, src/llamafactory/extras/env.py, src/llamafactory/launcher.py
=> [v1] add v1 folders

src/llamafactory/cli.py, src/llamafactory/launcher.py, src/llamafactory/v1/launcher.py
=> [v1] support switch v1 backend

src/llamafactory/extras/constants.py
=> [model] add qwen3-vl-30b

src/llamafactory/model/model_utils/moe.py
=> [misc] fix moe models

.github/workflows/docker.yml
Updated Docker workflow to include release type and change Python version to 3.10. Removed hardcoded latest tags in favor of versioned tags.
=> [ci] update docker workflow
