src/llmtuner/webui/manager.py

启动报错 refresh_dict["lang"] = {"value": user_config["lang"] if user_config["lang"] is None else "en"}
KeyError: 'lang'
修复代码

fix KeyError: 'lang' bug

---

src/llmtuner/tuner/ppo/utils.py

Fix parameters load error.
The method `torch.nn.Module.state_dict` 's return object is a shallow copy. It contains references to the module’s parameters and buffers. Use deep copy to avoid loading wrong default parameters.

Fix PPO replace_model loading wrong default parameters.

---

src/llmtuner/tuner/core/loader.py

This PR integrates Ascend NPU hardware capabilities into the LLaMA-Efficient-Tuning, and enables users to leverage the NPUs for training, inference and serving of LLMs.
[Ascend NPU](https://www.hiascend.com/en/) is an AI processor that support AI frameworks like PyTorch, TensorFlow, which has already integrated by [huggingface](https://github.com/huggingface/accelerate/commit/c33adecc9f92808cbaeb0d34928e52e34180f964), [deepspeed](https://github.com/microsoft/DeepSpeed/commit/23a11a39510e2aefb48236e3d2672a7dcbfc42a3) and others popular LLM related software and tools.
As mentioned above, Ascend NPU already supports libraries such as Transformers/Accelerate, so you can refer to the fine-tuning instructions in the README to perform LLM fine-tuning tasks directly on Ascend NPU.
The model …

Add Ascend NPU support

---

src/llmtuner/dsets/preprocess.py

Changing tokenizer's attribute at preprocessing stage will result in saving a wrong tokenizer. for example, baichuan2

fix tokenizer config changed after pretrain

---

src/llmtuner/extras/packages.py

To reproduce:
python:
importlib.util.find_spec('rouge-chinese') -> None
importlib.util.find_spec('rouge_chinese') -> ModuleSpec(name='rouge_chinese'...) from rouge_chinese import Rouge
print(Rouge.__module__) -> rouge_chinese

Fix: Change rouge-chinese package name to rouge_chinese

---

src/llmtuner/extras/misc.py

If using ```accelerate.Accelerator()```, it will cause the premature setting of the ```ACCELERATE_USE_DEEPSPEED ```environment variable, resulting in the regeneration of ```DeepSpeedPlugin``` and causing a change in the type of ```trainer.accelerator.state.deepspeed_plugin.hf_ds_config```
[source code: regeneration DeepSpeedPlugin](https://github.com/huggingface/accelerate/blob/3499cf25aa431ed3eeb7969f1d9b501ef20d0911/src/accelerate/accelerator.py#L284-L292)
[source code: HfTrainerDeepSpeedConfig  -> HfDeepSpeedConfig ](https://github.com/huggingface/accelerate/blob/3499cf25aa431ed3eeb7969f1d9b501ef20d0911/src/accelerate/utils/dataclasses.py#L600)
which can lead to errors similar to https://github.com/microsoft/DeepSpeed/issues/3733, https://github.com/hiyouga/LLaMA-Factory/issues/286. …

Improve get_current_device

---

src/llmtuner/webui/utils.py

The "CUDA_VISIBLE_DEVICES" in the "train_web.py interface [Preview]" button display is now set to prioritize reading from the environment variable.

Improve："CUDA_VISIBLE_DEVICES" read from the env

---

src/llmtuner/extras/misc.py

Improve warning messages when feeding in unknown arguments, will print all known args before throwing excpetion
Like this

Improve logging for unknown args

---

src/llmtuner/model/loader.py

Meet same problem: https://huggingface.co/mosaicml/mpt-7b-instruct/discussions/6
It costs about 1090ms
```py
model = AutoModelForCausalLM.from_pretrained(ckpt_dir, low_cpu_mem_usage=True, torch_dtype=torch.bfloat16)
```
But it costs about 264s+15s
```py
model = AutoModelForCausalLM.from_pretrained(ckpt_dir, low_cpu_mem_usage=True, torch_dtype=torch.float32)
model.to(torch.bfloat16)
```

Fix slow model initialization in bfloat16 dtype.

---

requirements.txt

einops dependency is needed foe phi-2 finetuning.

Update requirements.txt With einops dependency

---

README.md
README_zh.md

相关链接在这里
https://github.com/PKU-YuanGroup/Machine-Mindset?tab=readme-ov-file#%EF%B8%8F-acknowledgments

请求添加"Projects using LLaMA Factory"

---

src/llmtuner/model/patcher.py

support resize embeddings when using deepspeed zero3.
https://github.com/hiyouga/LLaMA-Factory/issues/1900

support resize embed for zero3

---

src/llmtuner/model/loader.py
src/llmtuner/model/patcher.py

[Deepspeed #4966](https://github.com/microsoft/DeepSpeed/pull/4966)
#1998

fix: ZeRO3 does not work with MoE models

---

data/README.md
data/dataset_info.json
src/llmtuner/data/aligner.py
src/llmtuner/data/parser.py
src/llmtuner/data/utils.py

SlimOrca uses the sharegpt format but encodes system prompts as messages. This was not supported so far.
This pull request adds `system_tag` as a tag for datasets, thus permitting system prompts to be encoded as messages. Previously an even number of messages was required for the sharegpt format. To accommodate for possible system messages, this was updated to permit an even number of non-system messages

Enable Parsing of SlimOrca

---

src/llmtuner/model/loader.py

Hi @hiyouga ! 
Great work on the Llama-Factory library ! 🚀
I would like to propose a new feature request: *model tagging*
With transformers 4.37.0 we added model tagging support by automatically tagging models on the Hub. That way you could sort models that have a specific tag, e.g. it you want to filter models that have the tag `trl` you could use think link: https://huggingface.co/models?other=trl / so for llama-factory: https://huggingface.co/models?other=llama-factory
I see it is already done in the `get_modelcard_args` method but `add_model_tags` enables you to push that tag even if you don't call `trainer.push_to_hub` and simply calling `model.push_to_hub()` will automatically push the model + the `llama-factory` tag
Let me know if this PR makes sense, otherwise we can also close it …

FEAT: add HF tags for models that have been trained with llama-factory

---

src/llmtuner/webui/chatter.py
src/llmtuner/webui/components/chatbot.py
src/llmtuner/webui/locales.py

allow user to create observation inputs on web ui to test the effectiveness of tuned model using tools.

support on fly test of tools

---

src/llmtuner/model/loader.py
src/llmtuner/model/patcher.py

fix deepspeed ppo RuntimeError: Expected all tensors to be on the same device, but found at least two devices
Fixes bug  in my experiment
when using deepspeed in ppo training,the model device map should not set，when the devce set 
it cause the runtime error problem 
but，when we not  set the device_map,it can work

fix deepspeed ppo RuntimeError

---

Dockerfile
docker-compose.yml
src/llmtuner/model/patcher.py

Here are some improvements based on the discussions of PR # (2743).
In addressing a compatibility issue, I made some slight alterations on the existing codes. Feel free to discuss with me.
Improve PR # (2743)

Improve Dockerize support

---

data/belle_multiturn/belle_multiturn.py
data/hh_rlhf_en/hh_rlhf_en.py
data/ultra_chat/ultra_chat.py

This Pull Request enhances the functionality of built-in datasets by aligning them with the HF_ENDPOINT environment variable. This adjustment facilitates more efficient dataset acquisition from https://huggingface.co/, particularly in settings where network connectivity is limited.
eg. When set HF_ENDPOINT to mirror "https://hf-mirror.com", built-in datasets will be downloaded through mirror along with models.

Follow HF_ENDPOINT environment variable

---

src/llmtuner/train/tuner.py

Fixes #2943 
已知默认生成配置会导致保存问题的模型:
- Llama2
- chinese-alpaca-2

修复了在 transformers > 4.36.2 版本中部分模型合并 Lora 模型时因生成配置校验而导致的崩溃问题

---

data/dataset_info.json

Refer to the Pile dataset [discussion](https://huggingface.co/datasets/EleutherAI/pile/discussions/15).
The Pile dataset originally hosted on Hugging Face is no longer downloadable. 
To address this issue, the original dataset configuration has been switched to an [alternative dataset](https://huggingface.co/datasets/monology/pile-uncopyrighted). 
Now, the Pile dataset can be downloaded normally.

Fix pile dataset download config

---

src/llmtuner/model/patcher.py

Enable the aux loss of mixtral model (in the same way as qwen-moe).
Config 'output_router_logits' of mixtral model defaults to False which turns off the aux loss.

fix: turn on output_router_logits of mixtral

---

src/llmtuner/data/template.py
src/llmtuner/extras/constants.py

Add template&support for c4ai-command-r/plus (tested)

---

README.md
README_zh.md
examples/README.md
examples/README_zh.md
examples/extras/MoD/freeze_sft.sh
examples/extras/MoD/sft.sh
src/llmtuner/hparams/model_args.py
src/llmtuner/hparams/parser.py
src/llmtuner/model/adapter.py
src/llmtuner/model/loader.py

Add support for Mixture of Depths
Atm if qwen is loaded an error is thrown, wen the qwen issue is resolved I'll remove it

Adding Mixture of Depth

---

data/dataset_info.json

Hi there,
I cannot find the "mlinmg/RLAIF-Nectar" on hf, seems like it changed as "AstraMindAI/RLAIF-Nectar". So, making a PR for updating.
See: https://huggingface.co/datasets/AstraMindAI/RLAIF-Nectar

update hf_hub_url for nectar_rm in dataset_info

---

Dockerfile

Fixed Dockerfile's CMD.
When I build a docker image using current CMD and run, below error occurs.
~~~
/opt/nvidia/nvidia_entrypoint.sh: line 49: /usr/local/bin/llamafactory-cli webui: No such file or directory
~~~
So, I splitted CMD in Dockerfile, and it worked well.
Fixes #3603

fix: splitted Dockerfile's CMD

---

src/llmtuner/extras/constants.py

Fix the download issue of the Phi-3 model
Fixes the download issue of the Phi-3 model

Update constants.py to fix the download issue of the Phi-3 model

---

src/llmtuner/webui/interface.py
src/webui.py

Fixes #3653
With Gradio,
- the `GRADIO_SERVER_PORT` is by default 7860 
- the `GRADIO_SHARE` is by default None (0)
So we don't really need these environment variables. Additionally, the `GRADIO_SERVER_PORT` is causing issues when I already have another gradio app running on my machine since they use 7860 by default. (Gradio documentation about these variables here: https://www.gradio.app/docs/gradio/interface#interface-launch-arguments)
By removing these manual presets and let Gradio handle the default values, the app works exactly the same but allows for more flexibility (automatically using next available port, such as 7861, when 7860 is already occupied by another app)
- [O] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING …

Remove Redundant Environment Variable Usage

---

src/train.py

The training efficiency of the Ascend 910A has been significantly enhanced by leveraging the full computational power of the NPU and the capabilities of torch_npu. This enhancement has led to a remarkable tenfold increase in training efficiency.

Enhancing Ascend 910A Training Efficiency in LlamaFactory with NPU

---

src/llamafactory/chat/vllm_engine.py
src/llamafactory/hparams/model_args.py

If the user train the llm with lora with lora rank greater than 16, the vLLM backend will fail to process with the error: `ValueError: LoRA rank XXX is greater than max_lora_rank 16`. This commit pass the `max_lora_rank` parameter to vLLM backend to support a higher lora rank (currently up to 64 due to the vLLM constraints).

feat: pass the `max_lora_rank` parameter to vLLM backend

---

src/llamafactory/chat/chat_model.py
src/llamafactory/chat/hf_engine.py
src/llamafactory/chat/vllm_engine.py
src/llamafactory/hparams/generating_args.py

support `system_message: "You are a helpful AI assistant."` in chat cli.

feat: cli chat support system_message

---

src/llamafactory/data/template.py
src/llamafactory/extras/constants.py

Add OpenChat-3.6-8B template `openchat-3.6` and  Model Group `OpenChat3.6-8B-Chat`.
[OpenChat-3.6-8B](https://huggingface.co/openchat/openchat-3.6-8b-20240522) is a new model from OpenChat team. The original `openchat` template is outdated for this model.

Add openchat-3.6-8B support

---

src/llamafactory/data/template.py

解决yi template错误，当前yi template缺少format_system，导致sft后保存的`tokenizer_config`文件中chat_tempalte字段的system_prompt前后缺少|im_start|与|im_end|，这不完全符合chatml格式，而Yi系统模型采用chatml
当前SFT后`tokenizer_config`的chat_template值：
```
"chat_template": "{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] %}{% endif %}{% if system_message is defined %}{{ system_message }}{% endif %}{% for message in messages %}{% set content = message['content'] %}{% if message['role'] == 'user' %}{{ '<|im_start|>user\\n' + content + '<|im_end|>\\n<|im_start|>assistant\\n' }}{% elif message['role'] == 'assistant' %}{{ content + '<|im_end|>' + '\\n' }}{% endif %}{% endfor %}",
```
此PR修改后：
```
 "chat_template": "{% if messages[0]['role'] == 'system' %}{% set system_message = messages[0]['content'] %}{% …
```

fix yi template

---

README.md
README_zh.md
setup.py

增加以下内容：
- Ascend NPU installation doc
- LLaMA-Factory installation with torch-npu in `setup.py`
安装完 LLaMA-Factory 之后，再 `pip install torch-npu`，直接使用该 python 环境会报错 CANN 初始化错误，该错误由缺少 decorator 依赖包引起，建议在setup中增加torch-npu对应的安装包，指定版本对齐及补充缺少的依赖
log：

Add Ascend npu doc and dependency

---

src/llamafactory/train/utils.py

When setting the argument `--lr_scheduler_type cosine_with_min_lr` for `python src/train.py`, the following error occurs:
```
ValueError: One of min_lr or min_lr_rate should be set through the `lr_scheduler_kwargs`
```
In response, I provided the argument `--lr_scheduler_kwargs '{"min_lr": 1e-7}'`, but an error still occurs because the `scheduler_specific_kwargs` argument is not properly passed to the `get_scheduler` function within the `create_custom_scheduler` function in `src/llamafactory/train/utils.py`.
To resolve this error, I have modified the code to set the `scheduler_specific_kwargs` argument to `training_args.lr_scheduler_kwargs` within the `create_custom_scheduler` function.

Set scheduler_specific_kwargs to get_scheduler

---

src/llamafactory/hparams/model_args.py
src/llamafactory/webui/components/export.py

Add npu option for model exporting
经测试，导出 qwen1.5-7b 模型 npu 和 cpu 的耗时如下（使用time统计的整个脚本执行时间）：
|   device   |   耗时   |
| ---- | ---- |
|   cpu   |   2m30.411s   |
|   npu   |   1m34.301s   |
```
ASCEND_RT_VISIBLE_DEVICES=0 llamafactory-cli export --model_name_or_path qwen/Qwen1.5-7B \
--adapter_name_or_path saves/Qwen1.5-7B/lora/sft \
--template qwen \
--finetuning_type lora \
--export_dir models/qwen1_5-7b_lora_sft \
--export_size 2 \
--export_device npu \
--export_legacy_format false
```
增加 npu 选项后，LlamaBoard 前端显示如图：

Add npu option for model exporting

---

src/llamafactory/data/processors/supervised.py

Fixes #2289 
Fixes #3957
使用贪心背包算法进行 sft packing，不会抛掉样本

supervised packing with greedy knapsack algorithm

---

MANIFEST.in

Ensures that requirements.txt and the LICENSE file are correctly included in the source distribution (sdist) when the package is built (and eg; published to pypi).
Without this, we cannot build a conda package because a wheel cannot be successfully built from the current sdist (requirements.txt file is referenced by setup.py but is missing in the sdist).
Tested that this change correctly includes the requirements.txt file in the sdist using the procedure in the linked issue.
Fixes #4190

Add MANIFEST.in so requirements.txt is present in sdist

---

src/llamafactory/data/processors/pretrain.py

llama3在预训练时使用的tokenizer.eos_toke是'<|end_of_text|>'，而Meta-Llama-3-8B-Instruct和很多llama3中文模型 都改成了<|eot_id|> ，进行增量预训练时应该使用'<|end_of_text|>' 。
经过大量的增量预训练，进行对比试验，发现这个bug：llama3在预训练时使用的tokenizer.eos_toke是'<|end_of_text|>' ，这里在每条数据后面也得用这个，而不是'<|eot_id|>'，否则增量预训练时很容易导致严重的性能下降
- [ √] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?

fixbug：llama3在增量预训练时应该使用<|end_of_text|>标识文本的结束

---

src/llamafactory/chat/vllm_engine.py

Fix #4238
vllm import changed today.
- https://github.com/vllm-project/vllm/blob/v0.5.0/vllm/sequence.py#L17C1-L18C1
before `from vllm.sequence import MultiModalData`
after `from vllm.multimodal import MultiModalData`

Support vllm==0.5.0

---

README.md
README_zh.md
data/dataset_info.json

Adds two dataset samples claimed superior performance: Magpie (from Allen AI) and Webinstruct (from TIGER-Lab).

Add Magpie and Webinstruct dataset samples

---

requirements.txt

Numpy 2.0.0 版本发布，与 torch 2.1.0 不兼容，会导致以下错误：
该升级只影响 torch-npu 的默认安装使用，不影响最新版 torch

update torch-npu dependencies

---

src/llamafactory/hparams/model_args.py
src/llamafactory/hparams/parser.py
src/llamafactory/model/model_utils/attention.py
tests/model/model_utils/test_attention.py

Bug Fix: `off` is parsed as `False` in yaml file, changed to `disabled` to avoid this.
I have tried to set `flash_attn` to `off`, and got error `Unknown attention type: False`.
Then this bug is found and fixed as submitted.
Reference:
[1] https://github.com/yaml/pyyaml/issues/376

Bug Fix: `off` is parsed as `False` in yaml file

---

src/llamafactory/chat/hf_engine.py
src/llamafactory/chat/vllm_engine.py
src/llamafactory/data/loader.py
src/llamafactory/data/template.py
src/llamafactory/hparams/data_args.py
tests/data/test_formatter.py

Added the `tool_format` parameter to rewrite templates for different function call formats.
- hf_engine:
```bash
python src/api.py --model_name_or_path GLM-4-9B --template glm4 --tool_format glm4
```
- vllm_engine
```bash
python src/api.py --model_name_or_path GLM-4-9B --template glm4 --infer_backend vllm --tool_format glm4
```
<details>
<summary>request code</summary>
```python
import json
from openai import OpenAI
base_url = "http://127.0.0.1:8000/v1/"
client = OpenAI(api_key="-1", base_url=base_url)
def function_chat():
messages = [{"role": "user", "content": "What's the weather like in Tokyo use celsius"}]
tools = [
{
"type": "function",
"function": {
"name": "get_current_weather",
"description": "Get the current weather",
"parameters": {
"type": "object",
"properties": {
"location": …
```

Add tool_format parameter to rewrite templates for different function call formats.

---

README.md
README_zh.md
docker/docker-cuda/Dockerfile
docker/docker-cuda/docker-compose.yml
docker/docker-npu/Dockerfile
docker/docker-npu/docker-compose.yml

Add dockerfile and docker-compose config file for Ascend NPU
cc @hiyouga 

Add docker-npu

---

README.md
README_zh.md
docker/docker-cuda/Dockerfile
docker/docker-cuda/docker-compose.yml

`flash-attn` is mandatory for some models.
Uninstalling and then rebuilding `flash-attn` (following [the installation](https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features)) satisfied the requirement and fixed #4242 #4264 completely.

support flash-attn in Dockerfile

---

src/llamafactory/chat/vllm_engine.py
src/llamafactory/extras/packages.py

Minimizes modifications to adapt to changes in vllm version 0.5.1 and later (regarding https://github.com/vllm-project/vllm/pull/5852).
Fixes addresses the error encountered when starting the web UI:
```
vllm_engine.py, line 33, in <module>
from vllm.multimodal.image import ImagePixelData
ImportError: cannot import name 'ImagePixelData' from 'vllm.multimodal.image'
```
**Specific Changes Made**
- **File:** `vllm_engine.py`
- Updated the import statement for `ImagePixelData` to handle changes in vllm version 0.5.1 and later.
- Introduced a conditional import to ensure compatibility with versions greater than 0.5.1 and 0.5.0.
- Updated the logic to handle ImagePixelData and MultiModalData correctly based on the vllm version.
- [ ✓ ] Did you read the [contributor …

chore: Update vllm_engine.py to support vllm version >= 0.5.1

---

src/llamafactory/train/callbacks.py

在 examples/train_lora/llama3_lora_reward.yaml 中添加了一行配置使用`deepspeed`， 训练完成后保存模型不成功，报错`TypeError:str.replace()takes no keyword arguments`。配置如下
``` yaml
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
stage: rm
do_train: true
deepspeed: examples/deepspeed/ds_z3_config.json
dataset: dpo_en_demo
template: llama3
cutoff_len: 1024
max_samples: 50
output_dir: saves/llama3-8b/lora/rewardfix
overwrite_output_dir: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps …
```

fix src/llamafactory/train/callbacks.py

---

src/llamafactory/webui/utils.py

In windows mutiline command should like
```
llamafactory-cli train `
--stage sft `
--do_train True `
```

Fix Windows command preview

---

data/README.md
data/README_zh.md
data/dataset_info.json
scripts/cal_lr.py
scripts/cal_ppl.py
scripts/length_cdf.py
src/llamafactory/data/data_utils.py
src/llamafactory/data/loader.py
src/llamafactory/data/parser.py
src/llamafactory/data/preprocess.py
src/llamafactory/hparams/data_args.py
src/llamafactory/train/dpo/workflow.py
src/llamafactory/train/kto/workflow.py
src/llamafactory/train/ppo/workflow.py
src/llamafactory/train/pt/workflow.py
src/llamafactory/train/rm/workflow.py
src/llamafactory/train/sft/workflow.py
tests/data/test_supervised.py

2. merge load dataset and split dataset function
1. add custom eval dataset support during training
2. reconstruct the load dataset and split dataset functions
fix #2290 
fix #3974

add eval dataset support

---

examples/train_lora/llama3_lora_eval.yaml
src/llamafactory/eval/evaluator.py
src/llamafactory/hparams/data_args.py

1. add "split" as suffix in eval task name
2. remove "split" param in data_args.py

add "split" as suffix in eval task name

---

src/llamafactory/data/processors/supervised.py
src/llamafactory/hparams/data_args.py
src/llamafactory/hparams/parser.py
src/llamafactory/webui/components/train.py
src/llamafactory/webui/locales.py
src/llamafactory/webui/runner.py

When using RAG, we typically need to attach the retrieved content to the system role's prompt. This causes the system prompt to frequently change, so training only the last turn of the conversation helps to fine-tune RAG's capabilities.
I add a mode to only fine-turning the last turn conversation.

Train the last turing conversation.

---

.gitignore
README.md
docker/docker-rocm/Dockerfile
docker/docker-rocm/docker-compose.yml

Added a docker build with a demonstration of running the project on AMD video cards using ROCm.
Tested on AMD Radeon RX 7900 XTX.

Add ROCm support

---

src/llamafactory/webui/components/export.py

fix #4728 : Repair the issue where quantization failed after merging the adapter.

fix: Repair the issue where quantization failed after merging the adapter.

---

src/llamafactory/webui/components/top.py
src/llamafactory/webui/locales.py

[Add] This PR adds Korean translations for the web UI in the `llamafactory-cli webui`.
This pull request enhances the web UI by including Korean translations for all interface elements. 
It ensures that Korean users can fully interact with the llamafactory in their native language.
- Added Korean translations for all UI elements.
> Updated the `LOCALES` dictionary to include Korean (`ko`) entries. (src/llamafactory/webui/locales.py)
>  Ensured consistency and accuracy of the translations.

Add Korean web UI (llamafactory-cli webui)

---

src/llamafactory/data/template.py

I fixed the template for DeepSeek-Coder. The reference link for the template is as follows:
https://github.com/deepseek-ai/DeepSeek-Coder/blob/b7ba565956fe61153064f288862daf1896de5393/finetune/finetune_deepseekcoder.py#L16
The main change was the addition of the `"<|EOT|>"` token, which ensures that the trained model does not generate infinitely due to the lack of an end-of-sequence marker. I have trained the relevant models and compared them, finding that the new version of the template perfectly solves the problem.

fix the deepseekcoder template to avoid repeat problem

---

src/llamafactory/data/loader.py
src/llamafactory/data/processors/supervised.py
src/llamafactory/data/template.py
src/llamafactory/hparams/data_args.py

#4878 提出的 ”仅最后一轮参与训练“ 可以满足 Distillation、Reflective Chain 等场景的需求，但其实现方法存在一个小问题：
当对话总长度超过 `cutoff_len`，会退出遍历 `encoded_pairs` 的循环（截断），则最重要的最后一段对话无法加入训练数据中，且 `label` 全为 `IGNORE_INDEX`，该条数据无意义。
针对截断问题，即在保留最后一段对话的前提下，可行的解决方案有：
1. 反向遍历 `encoded_pairs` ，新增元素从头部插入 `input_ids`和`labels`，其余逻辑不变；
2. 最大化截断后所保留的对话轮次，即删除较长的单轮对话；
PR 了采取第一种方法，以最小化改动对原代码的侵入性。
Fixes #4684

fix: `Train on the last turn only` truncate bug

---

src/llamafactory/data/template.py
src/llamafactory/hparams/finetuning_args.py
src/llamafactory/train/dpo/trainer.py
src/llamafactory/train/kto/trainer.py
src/llamafactory/train/ppo/trainer.py
src/llamafactory/train/pt/trainer.py
src/llamafactory/train/rm/trainer.py
src/llamafactory/train/sft/trainer.py
src/llamafactory/train/trainer_utils.py

Fix: Rename the `optimzer` to `optimizer`
Feat: #4696 
https://github.com/zyushun/Adam-mini
Use follow command to install adam_mini.
```
pip install -e git+https://github.com/zyushun/Adam-mini.git#egg=adam_mini
```
Now you can train the model with `--use_adammini True` now.
This optimizer still has a lot of room for improvement, but as of now, it is not as good as Unsloth.
But if you can't use Unsloth, it will be a good way to replace adawm_torch.
https://github.com/zyushun/Adam-mini/issues/11

Feat optimizer

---

src/llamafactory/extras/misc.py

`transformers.utils.is_torch_bf16_gpu_available` currently only supports checking for GPU/CUDA availability, and `transformers` do not provide a similar interface for NPU. This results in `llama-factory` incorrectly determining that the device does not support NPU (such as Ascend 910B) when using NPU for inference. That is, when inferencing without specifying `infer_dtype`, it will automatically fall back to `fp16` instead of `bf16`.

_is_bf16_available judgment supports npu

---

src/llamafactory/extras/misc.py

Reports correct device count for Intel OneAPI devices.

fix: report correct device count for intel xpu

---

src/llamafactory/data/template.py

This PR adds a new template for SailorLLM to the repository, which enhances the system's ability to format user and system inputs according to the SailorLLM format. This template uses the following structure:
- **User Format:** `<|im_start|>question\n{{content}}<|im_end|>\n<|im_start|>answer\n`
- **System Format:** `<|im_start|>system\n{{content}}<|im_end|>\n`
- **Separator:** `\n`
- **Stop Words:** `["<|im_end|>"]`
- **Replace EOS:** `True`
This addition is based on the SailorLLM's formatting style, as referenced from the [SailorLLM repository](https://github.com/sail-sg/sailor-llm).
**SailorLLM** is a suite of Open Language Models for South-East Asia (SEA), focusing on languages like Indonesian, Thai, Vietnamese, Malay, and Lao. Built on Qwen 1.5, Sailor models range from 0.5B to 14B …

Add SailorLLM template

---

src/llamafactory/data/template.py

Llama 模型对应的 jinjia 模板有误，会导致系统提示被覆盖。
目前 Llama 的 jinjia 模板：
```jinja2
{% set system_message = '[template.default_system]' %}
{% if messages[0]['role'] == 'system' %}
{% set system_message = messages[0]['content'] %}
{% endif %}
{% for message in messages %}
{% set content = message['content'] %}
{% if loop.index0 == 0 and system_message is defined %}
{% set content = '<<SYS>>\n' + system_message + '\n<</SYS>>\n\n' + message['content'] %}
{% endif %}
{% if message['role'] == 'user' %}
{{ '[INST] ' + content + ' [/INST]' }}
{% elif message['role'] == 'assistant' %}
{{ content + '' }}
{% endif %}
{% endfor %}
```
该方法只能满足默认的`system_message`，用户自定义的 `system_message` 会被后一轮 user 覆盖。
为解决这一问题，修改了判断条件，自定义系统提示词时，跳过第一轮。
[#5123](https://github.com/hiyouga/LLaMA-Factory/issues/5123)

fix Llama-template's system prompt bug

---

src/llamafactory/api/chat.py

In `ChatModel.achat` should input `image: Optional["NDArray"]` but in following code it return PIL.Image directly.
https://github.com/hiyouga/LLaMA-Factory/blob/36039b0fe01c17ae30dba60e247d7ba8a1beb20a/src/llamafactory/api/chat.py#L115

Fix mllm api

---

data/dataset_info.json
data/qwen2vl_demo.json
examples/train_full/qwen2vl_full_sft.yaml
examples/train_lora/qwen2vl_lora_sft.yaml
src/llamafactory/data/collator.py
src/llamafactory/data/processors/processor_utils.py
src/llamafactory/data/processors/supervised.py
src/llamafactory/data/template.py
src/llamafactory/model/adapter.py
src/llamafactory/model/model_utils/misc.py

This PR support the coming [qwen2-vl](https://github.com/huggingface/transformers/pull/32318) model for fine-tuning.

support qwen2-vl

---

README.md

so users can check more info if they are curious

Add liger kernel link

---

src/llamafactory/chat/hf_engine.py
src/llamafactory/data/aligner.py
src/llamafactory/data/collator.py
src/llamafactory/data/loader.py
src/llamafactory/data/mm_plugin.py
src/llamafactory/data/processors/feedback.py
src/llamafactory/data/processors/pairwise.py
src/llamafactory/data/processors/pretrain.py
src/llamafactory/data/processors/supervised.py
src/llamafactory/data/processors/unsupervised.py
src/llamafactory/hparams/data_args.py
src/llamafactory/train/dpo/workflow.py
src/llamafactory/train/kto/workflow.py
src/llamafactory/train/ppo/workflow.py
src/llamafactory/train/pt/workflow.py
src/llamafactory/train/rm/workflow.py
src/llamafactory/train/sft/workflow.py
src/llamafactory/train/test_utils.py
tests/data/test_mm_plugin.py

Fixes #5308 
Fixes #5331 
In this PR, we moved the image processor's `forward` step from the pre-processing phase to the training phase, thereby saving disk space for cached datasets. However, it could affect training throughput.
Moreover, we introduced a `preprocessing_batch_size` argument to control the batch size during the pre-processing phase, to prevent process hangs.
To use dataset streaming for multimodal datasets, the best practice is:
```yaml
dataset: your_dataset
buffer_size: 128
preprocessing_batch_size: 128
streaming: true
accelerator_config:
dispatch_batches: false
```
`dispatch_batches: false` is necessary for multimodal datasets since the batch size of images may differ from that of input ids. 
https://huggingface.co/docs/transformers/main_classes/trainer#transformers.Train …

[exp] Lazyload for multimodal inputs

---

src/llamafactory/data/loader.py
src/llamafactory/hparams/data_args.py

Add batch size arguments for map function in the _get_preprocessed_dataset.
- Some of machine can't accept the default batch size(1000) of dataset map function. 
- Therefore, users should be able to modify the batch size of the map function through external arguments.

Add batch size of map function in the preprocessed dataset

---

docker/docker-rocm/Dockerfile

When upgrading to the latest version of ROCm, the vLLM installation error was fixed.
Tested on AMD Radeon RX 7900 XTX.
The image is assembled without errors when setting the arguments to true
```
services:
llamafactory:
build:
dockerfile: ./docker/docker-rocm/Dockerfile
context: ../..
args:
INSTALL_BNB: true
INSTALL_VLLM: true
INSTALL_DEEPSPEED: true
INSTALL_FLASHATTN: true
```

Update the ROCm version to 6.2

---

src/llamafactory/data/formatter.py

functioncall数据训练的时候，如果function message的json字符串不合法，比如中间有些非法json控制字符比如换行；json.load无法加载，此时置空functions不报任何错误会让用户很疑惑，难以定位。
故抛出RuntimeError异常
- [ x] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [x ] Did you write any new necessary tests?

fix: 修复function call数据集如果 function_call 值的为不合法json，异常提示且中断训练。

---

src/llamafactory/model/model_utils/attention.py

When the model_args.flash_attn is already set to fa2 we shouldn't output a warning about it.

made a small change to a warning about fa2 for gemma2 models.

---

docker/docker-cuda/Dockerfile

default `BASE_IMAGE` is nvcr.io/nvidia/pytorch:24.02-py3 for retro-compatibility

make base image parametric.

---

src/llamafactory/chat/vllm_engine.py

在vllm 0.6.3版本的vllm.AsyncLLMEngine.generate函数中，将inputs参数换成了prompt参数。现将LLaMA-Factory也同步更改一下。
- [ √] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [× ] Did you write any new necessary tests?

fix VllmEngine: 将inputs参数替换为prompt

---

src/llamafactory/extras/misc.py
src/llamafactory/hparams/finetuning_args.py
src/llamafactory/train/dpo/workflow.py
src/llamafactory/train/sft/workflow.py

support efficient tokens calculation on sft and dpo.

support effective tokens calculation on sft/dpo

---

.gitignore
README.md
README_zh.md
src/llamafactory/chat/hf_engine.py
src/llamafactory/data/collator.py
src/llamafactory/data/mm_plugin.py
src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/extras/packages.py
src/llamafactory/hparams/model_args.py
src/llamafactory/model/model_utils/longlora.py
src/llamafactory/model/model_utils/misc.py
src/llamafactory/model/model_utils/packing.py
src/llamafactory/model/model_utils/visual.py
src/llamafactory/model/patcher.py

Support Llama-3.2-11B-Vision.
#5549
bitsandbytes 8 bits quantization is not functional. 4 bits is okay but not 8 bits.

Support llama3.2 vision

---

docker/docker-cuda/docker-compose.yml
docker/docker-npu/docker-compose.yml
docker/docker-rocm/docker-compose.yml

Fixes #4316
This pull request increases the shm_size parameter in docker-compose.yml to 16GB. The goal is to enhance the LLaMA-Factory framework’s performance for large model fine-tuning tasks by providing sufficient shared memory for efficient data loading and parallel processing.
This PR also addresses the issues discussed in [[this comment](https://github.com/hiyouga/LLaMA-Factory/issues/4316#issuecomment-2466270708)](https://github.com/hiyouga/LLaMA-Factory/issues/4316#issuecomment-2466270708) regarding Shared Memory Limit error.

Increase shm_size to 16GB in docker-compose.yml

---

src/llamafactory/data/collator.py
src/llamafactory/train/sft/trainer.py
src/llamafactory/train/sft/workflow.py

[model] fix qwen2vl infern

---

src/llamafactory/api/chat.py
src/llamafactory/data/formatter.py
src/llamafactory/data/template.py
src/llamafactory/data/tool_utils.py
src/llamafactory/webui/chatter.py
tests/data/test_formatter.py

Support Mistral format tools
```
<s>[AVAILABLE_TOOLS] [{"type": "function", "function": {"name": "get_news", "description": "获取最新新闻文章", "parameters": {"type": "object", "properties": {"category": {"type": "string", "description": "要检索的新闻文章类别"}, "country": {"type": "string", "description": "获取新闻文章的国家"}}, "required": ["category"]}}}, {"type": "function", "function": {"name": "search_books", "description": "根据提供的标准搜索书籍", "parameters": {"type": "object", "properties": {"title": {"type": "string", "description": "这本书的标题"}, "author": {"type": "string", "description": "这本书的作者"}, "genre": {"type": "string", "description": "这本书的类型"}}}}}][/AVAILABLE_TOOLS][INST] 你能帮我找到最新的美国体育新闻吗？[/INST][TOOL_CALLS] [{"name": "get_news", "arguments": {"category": "运动", "country": "美国"}}][TOOL_RESULTS] {"content": …
```

Support Mistral format tools

---

.gitignore
src/llamafactory/hparams/finetuning_args.py
src/llamafactory/train/dpo/trainer.py
src/llamafactory/train/kto/trainer.py
src/llamafactory/train/pt/trainer.py
src/llamafactory/train/rm/trainer.py
src/llamafactory/train/sft/trainer.py
tests/e2e/test_train.py
tests/train/test_sft_trainer.py

Add parameter `disable_shuffling` to LlamaFactory
Fixes #1204 
Fixes #3306 
Fixes #5121

[trainer] support disable shuffling

---

src/llamafactory/hparams/finetuning_args.py
src/llamafactory/train/dpo/trainer.py
src/llamafactory/train/kto/trainer.py
src/llamafactory/train/ppo/trainer.py
src/llamafactory/train/pt/trainer.py
src/llamafactory/train/rm/trainer.py
src/llamafactory/train/sft/trainer.py
src/llamafactory/train/trainer_utils.py
src/llamafactory/webui/components/train.py
src/llamafactory/webui/locales.py
src/llamafactory/webui/runner.py

[SwanLab](https://github.com/swanhubx/swanlab) 是一个开源的模型训练记录工具，面向AI研究者，提供了训练可视化、自动日志记录、超参数记录、实验对比、多人协同等功能。在SwanLab上，研究者能基于直观的可视化图表发现训练问题，对比多个实验找到研究灵感，并通过在线链接的分享与基于组织的多人协同训练，打破团队沟通的壁垒。
**为什么要记录训练**
相较于软件开发，模型训练更像一个实验科学。一个品质优秀的模型背后，往往是成千上万次实验。研究者需要不断尝试、记录、对比，积累经验，才能找到最佳的模型结构、超参数与数据配比。在这之中，如何高效进行记录与对比，对于研究效率的提升至关重要。
**在LLaMA Factory中使用**
**方式一：CLI**
在yaml配置文件中，增加如下代码（注释的部分，代表选填）：
```yaml
use_swanlab: true
swanlab_project: LLaMA-Factory
```
然后CLI启动命令即可：
```bash
llamafactory-cli train your_config.yaml
```
**方式二：WebUI**
启动WebUI：
```bash
llamafactory-cli webui
```
在GUI中对应栏位填写参数后，启动训练后，在系统的命令行打印中找到SwanLab实验链接访问即可：
**SwanLab API Key如何获取**
在[官网](https://swanlab.cn)或[备用官网](https://swanlab.115.zone)注册/登录账号，在设置中找到API Key。
如果你使用local模式，则无需 API Key。
**一些交互上的想法**
如果在「SwanLab …

feat: add swanlab for experiment tracking and visualization.

---

src/llamafactory/cli.py

Right now we cannot invoke llama factory via `python` directly.
With this PR, we can use `python -m llamafactory.cli` , which is required for using debugger like vscode [debugger](https://github.com/microsoft/debugpy)

[misc] enable module run

---

docker/docker-cuda/Dockerfile
docker/docker-npu/Dockerfile
docker/docker-rocm/Dockerfile

Add ARG HTTP_PROXY in Dockerfile to support HTTP proxy during image building.
This commit introduces an ARG parameter named HTTP_PROXY in the Dockerfile. This addition allows for the configuration of an HTTP proxy, facilitating image building in environments with network restrictions.  

Add ARG HTTP_PROXY in Dockerfile to support HTTP proxy during image building

---

README.md
README_zh.md
examples/train_qlora/llama3_lora_sft_otfq_npu.yaml
src/llamafactory/model/model_utils/longlora.py

Fixes #6452 
1. Add QLoRA Support on Ascend NPU
2. Add a transformers version check of the import dependencies for LlamaFlashAttention2 and LlamaSdpaAttention, as these two attention modules have been removed from modeling_llama.py in the latest version of transformers.

add nf4 qlora support on Ascend NPU

---

src/llamafactory/model/loader.py

Fixes #6415
It modifies logic of `loader.py -> load_tokenizer(...)` to update `tokenizer.model_max_length` if `model_args.model_max_length` changes.

Update tokenizer.model_max_length if necessary (Fix #6415)

---

src/llamafactory/data/processors/pretrain.py
src/llamafactory/hparams/model_args.py
src/llamafactory/model/loader.py
src/llamafactory/model/model_utils/rope.py
src/llamafactory/model/patcher.py
src/llamafactory/webui/chatter.py
src/llamafactory/webui/common.py
src/llamafactory/webui/components/export.py
src/llamafactory/webui/components/top.py
src/llamafactory/webui/locales.py
src/llamafactory/webui/runner.py

[model] support yarn

---

src/llamafactory/train/dpo/trainer.py

Fix: Avoid Redundant Normalization in DPO's SFT Loss Calculation
Problem
In the current implementation, the SFT loss in DPO is computed as chosen_logps / chosen_length. However, for specific loss types such as ["ipo", "orpo", "simpo"], the all_logps tensor is already normalized by dividing it by valid_length earlier in the code. When chosen_logps is further divided by chosen_length in the return statement, it results in redundant normalization, which leads to incorrect results.
Solution
This PR introduces a conditional check in the return statement to handle this case:
For ["ipo", "orpo", "simpo"]: The already normalized chosen_logps is returned directly without further division.
For all other loss types (e.g., DPO): The original behavior is preserved, and chosen_logps / chosen_length is …

fix: avoid redundant normalization in DPO's SFT loss calculation

---

README.md
README_zh.md

Fixes #6092
这一类的问题大概都是这个原因，印象中在 issue 看到过好几次
原始连接中的预编译版本 FA2 只支持推理，不支持训练，用于训练就会导致上面的问题
应该已经持续了有一段时间了，至少好几个月，很奇怪为什么没人指出来，我自己也是花了很久才发现问题之所在
而且因为 [LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory) 的知名度，已经开始扩散到其他场景了，在其他项目的 issue 下也看到了类似问题，反应是按照 [LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory) 的文档安装的 FA2
不过 FA2 编译的还是挺慢的，建议作者自己维护几个常用的预编译版本组合，应该可以减少处理相关 issue 的时间

docs: 修正 Windows 平台上 FA2 的安装说明 

---

src/llamafactory/data/tool_utils.py
tests/data/test_formatter.py

Modify QWEN_TOOL_PROMPT to have aligned format with hf apply chat template.
Currently, the qwen template output does not align with the hf apply chat template output when tools are included. Specifically, `QWEN_TOOL_PROMPT` in `LLaMA-Factory/src/llamafactory/data/tool_utils.py contains` `<|im_end|>\n` at the end, and `self.format_system` in `LLaMA-Factory/src/llamafactory/data/template.py` will add another `<|im_end|>\n` to the end of the formatted system prompt, causing there to be two sets of `<|im_end|>\n` in the system prompt when using tools.
N/A
- [] Did you write any new necessary tests?

Update QWEN_TOOL_PROMPT 

---

src/llamafactory/data/mm_plugin.py

Fixes #6860
Calculate the actual fps for each video and get correct `second_per_grid_ts`
The origin solution directly use `video_fps`, this may be incorrect when meeting long video.
The modified version works on my project.
- [] Did you write any new necessary tests?

fix qwen_2_5_vl video processing

---

pyproject.toml
src/llamafactory/data/converter.py

Improve error handling for missing image files in _convert_images
- Refactor path handling logic to enhance readability.
- Log a warning when image files are not found in specified directory, maintaining the original path.

Improve error handling for missing image files in _convert_images

---

src/llamafactory/data/loader.py

`If you pass a dictionary with names of datasets as keys and datasets as values, evaluate will run separate evaluations on each dataset. This can be useful to monitor how training affects other datasets or simply to get a more fine-grained evaluation`
seq2seqtrainner support eval_dataset as Dict.
- [ ✅ ] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [ ✅ ] Did you write any new necessary tests?
- I test it in **alpacha format data**，mode **sft**, model qwen2.5-7B-Instruct ，both **single GPU** and **2 GPU using fsdp**. 
- the loss will be print and be logged in tensorboard run logs, which can be filtered by `_loss` in your tensorboard webUI.

[data] evaluate on each dataset

---

src/llamafactory/train/sft/trainer.py
src/llamafactory/train/sft/workflow.py

Fixes #5444 
The current impl disregards whatever user might have set in the yaml config during evaluations that happen during training (as specified by user e.g. every 100 step eval once)
Instead, it is only applied correctly at the final eval after training is done.
This should not be the case as that would make any intermediate eval results inaccurate.

Correctly pass gen_kwarg to eval during model runs

---

src/llamafactory/hparams/training_args.py
src/llamafactory/train/trainer_utils.py

Adds ability to specify the `storage_path` argument in the ray `TorchTrainer` [RunConfig](https://docs.ray.io/en/latest/train/api/doc/ray.train.RunConfig.html#ray.train.RunConfig). This specifies the path to save checkpoints to, and is needed to save to shared cluster storage when dealing with multi-node training.

add ability to specify ray storage path

---

README.md
docker/docker-npu/Dockerfile
docker/docker-npu/docker-compose.yml
setup.py

1.Update base npu container image version:The Python version required for Hugging Face Transformers is >= python3.10
2.fix the type error of args INSTALL_DEEPSPEED of npu docker-compose.yaml: should been string
- [*] Did you read the [contributor guideline](https://github.com/hiyouga/LLaMA-Factory/blob/main/.github/CONTRIBUTING.md)?
- [*] Did you write any new necessary tests?

[NPU] update cann base image to py3.10 and fix the type error of args INSTALL_DEEPSPEED of npu docker-compose.yaml

---

src/llamafactory/extras/constants.py
src/llamafactory/train/trainer_utils.py
src/llamafactory/webui/components/train.py
src/llamafactory/webui/control.py
src/llamafactory/webui/locales.py
src/llamafactory/webui/runner.py

This PR adds a "SwanLab Link" Textbox to the SwanLab module in the WebUI.  
The Textbox retrieves and displays the SwanLab experiment link in the WebUI after training starts:
Additional details:
1. A new `LLaMAFactorySwanLabCallback` class is introduced to save `swanlab_public_config.json` to the output directory when creating a SwanLab experiment.
2. When `use_swanlab` is disabled, the "SwanLab Link" displays "not using swanlab".
3. When `use_swanlab` is enabled and `local` mode is selected, the "SwanLab Link" displays "only show link in cloud mode".
4. While waiting for the experiment link to be generated, the "SwanLab Link" displays "waiting".

feat: webui add swanlab link

---

src/llamafactory/data/mm_plugin.py
src/llamafactory/data/processor/pairwise.py

[data]Repair multimodal model dpo training
Fixes #7072 
process_messages方法传参为可变对象（list），在chosen调用时内部修改了prompt，导致rejected再次调用时报错
可能影响所有多模态模型偏好训练

[data]Repair multimodal model dpo training

---

src/llamafactory/chat/hf_engine.py
src/llamafactory/chat/vllm_engine.py
src/llamafactory/webui/chatter.py
src/llamafactory/webui/components/chatbot.py
src/llamafactory/webui/locales.py

[webui] support escape html

---

src/llamafactory/data/formatter.py

This PR fix a issue of think tag splicing in FunctionFormatter.apply
Fixes #7064

Fix the issue of missing think tag in FunctionFormatter.apply

---

src/llamafactory/data/collator.py

While running SFT with just `packing` vs `neat_packing`, we observe a significant speed difference, upon inspection looks like the rate determining step seems to be `prepare_4d_attention_mask` method.
This PR improves the existing implementation and also does computation on `compute_device` if available.
Stats on our dataset:
batch_size: 1, cutoff_len: 26k
1. current implementation:  ~18.7s per call (as collator runs on CPU)
2. proposed implementation without GPU: ~3.3s per call
3. proposed implementation with GPU: ~0.76s per call

efficient 4d_attention_mask creation in neat_packing

---

setup.py

Fixes Running SGLang.
- SGLang requires SGLang Runtime (`srt`)
- https://github.com/sgl-project/sglang/issues/4629 : transformers version conflict reported in sglang community
```
ValueError: '<class 'sglang.srt.configs.qwen2_5_vl_config.Qwen2_5_VLConfig'>' is already used by a Transformers model
```
And the suggested workaround is to use `transformers==4.48.3`.

Running SGLang

---

scripts/eval_bleu_rouge.py

手动提取了bleu和rouge评分逻辑并独立放在`script/eval_bleu_rouge.py`里
方便在使用`vllm_infer.py`生成结果时手动进行评分
可以避免直接使用配置文件时生成速度缓慢的问题
https://github.com/hiyouga/LLaMA-Factory/issues/7418
仅检查了需要的几个第三方库是否安装

允许手动对vllm_infer.py生成的jsonl文件进行评分

---

docker/docker-cuda/Dockerfile

Because flatten_with_keys_fn causes an error depending on the torch version, the NVIDIA official image used was updated to PyTorch 2.6.0, pytorch:24.12-py3.
https://github.com/huggingface/transformers/issues/36888

nvidia cuda image update with transformer upgrade to 4.50.0

---

src/llamafactory/model/model_utils/liger_kernel.py

This is a preperation for the [PR](https://github.com/linkedin/Liger-Kernel/pull/621) of Gemma3 support in Liger-Kernel repositoy, which passed the tests and waiting to be merged and release as a new version.
I had tested it on my machine with RTX3090 by finetuing a Gemma3 model with Llama-factory, I can see the log message that Liger-Kernel has been applied to the model, and also the reductions to occupied VRAM and increased throughput, as expected.
As the PR in Liger-Kernel has been reviewed, the monkey patch with `apply_liger_kernel_to_gemma3` is unlikely to change.
We can wait for the Liger Kernel release and then merge this PR.

Enable Liger-Kernel for Gemma3

---

src/llamafactory/train/trainer_utils.py

Fixes #5548
Warmup_stable_decay supports setting the number of stable and decay steps according to the warmup_ratio ratio.
- use
```
lr_scheduler_type: warmup_stable_decay
lr_scheduler_kwargs:
num_cycles: 0.5
warmup_ratio: 0.2
```
- effect
```py
num_warmup_steps = training_args.get_warmup_steps(num_training_steps)
remaining_steps = num_training_steps - num_warmup_steps
num_stable_steps = remaining_steps // 3
num_decay_steps = remaining_steps - num_stable_steps
```

[trainer] Warmup_stable_decay supports setting the number of stable and decay steps according to the warmup_ratio ratio

---

src/llamafactory/data/processor/feedback.py

During KTO training, `FeedbackDatasetProcessor` calculates the KL term by reversing the labels. This usually works, except on odd batch sizes, in which case the middle will be a match.
And this has been updated in [huggingface/trl](https://github.com/huggingface/trl) by [this PR](https://github.com/huggingface/trl/pull/1970) according to [this issue](https://github.com/huggingface/trl/issues/1911).
YES
NO, there is no new necessary test.

New mismatch pair creation strategy

---

README.md
README_zh.md
src/llamafactory/data/loader.py
src/llamafactory/hparams/data_args.py

This addresses a limitation introduced by https://github.com/hiyouga/LLaMA-Factory/pull/5346
Currently, if you use streaming, you cannot do multiprocessing by setting `dataloader_num_workers` as they will always be restricted to one worker due to the dataset not being sharded. As a result, user will see `Too many dataloader workers: XXX (max is dataset.num_shards=1). Stopping XXX dataloader workers`.
This causes anyone who tries to stream data to suffer a huge speed bottleneck as preprocessing is basically limited to one CPU core per process, especially on preprocessing-heavy datasets like videos. There is also no indication when this is happening, so to the users, it seems like their code is stuck.
In order to allow for multiple dataloader workers to work on a streaming dataset, it must …

Shard the dataset to allow multiprocessing when streaming is enabled

---

src/llamafactory/data/collator.py
src/llamafactory/data/processor/supervised.py

In current `neat_packing` we don't use `position_ids` along with the 4D attention mask, 
Even though the 4D mask prevents cross sequence attention, `neat_packing` is still different from no packing, since the model perceives (position encoding difference) later sentence position different in comparison to no packing. 
In this PR, we add `position_ids` for sentences when `neat_packing` is specified, which allows the tokens position to be perceived (proper position encoding) properly as if there's no packing.

[data] specify position_ids in PackedSupervisedDatasetProcessor for neat_packing

---

src/llamafactory/model/patcher.py

Enable setting use_cache correctly for `Gemma3ForConditionalGeneration` models
Yes
Yes

fix use_cache patching for gemma3 multimodal

---

src/llamafactory/train/ppo/trainer.py

Fixes #6881
This PR fixes a bug in the PPO trainer's mini-batch handling where slicing operations could fail when `labels` are `None`. 
Previously, when passing the batch directly to `get_inputs()` using slice notation:
```python
mini_batch_queries, mini_batch_responses = self.get_inputs(
batch[idx : idx + self.config.mini_batch_size]
)
```
This would attempt to slice all elements in the batch dictionary, including `labels` which could be `None`. The issue occurs because of how the transformers library handles dictionary slicing in `BatchEncoding.__getitem__`:
```python
def __getitem__(self, item: Union[int, str]) -> Union[Any, EncodingFast]:
elif isinstance(item, slice):
return {key: self.data[key][item] for key in self.data.keys()}  # This fails when data[key] is None
```
When a slice …

[trainer] Refactor mini-batch input handling in PPO trainer

---

scripts/qwen_omni_merge.py
src/llamafactory/data/collator.py
src/llamafactory/data/mm_plugin.py
src/llamafactory/model/loader.py

1. align the `video_second_per_grid` and `second_per_grids` with `second_per_grid_ts`, they should be the same thing.
2. specify the `qwen2_omni` entry for now in `loader.py`.
3. update the scripts for merging [`thinker`, `thinker_lora`,  base_model  | `thinker_ft`, base_model ].
```bash
python3 ./scripts/qwen_omni_full.py merge_lora \
--base_model_path="./Qwen2_5Omni" \
--lora_checkpoint_path="./lora_checkpoint" \
--save_path="./target_dir"
python3 ./scripts/qwen_omni_full.py save_full \
--base_model_path="./Qwen2_5Omni" \
--saved_thinker_path="./saved_thinker" \
--save_path="./target_dir"
```

[data] Qwen2_5Omni nit

---

src/llamafactory/data/collator.py
src/llamafactory/data/mm_plugin.py

Change some field names and fix the video SFT error.
```yaml
stage: sft
do_train: true
lora_rank: 8
dataset:  mllm_video_demo, mllm_demo, identity, mllm_audio_demo
cutoff_len: 3072
```

Qwen2Omni nit for video_grids

---

requirements.txt
scripts/convert_ckpt/tiny_llama4.py
src/llamafactory/__init__.py
src/llamafactory/data/mm_plugin.py
src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/extras/misc.py
src/llamafactory/model/model_utils/checkpointing.py
src/llamafactory/model/model_utils/visual.py
src/llamafactory/train/ppo/trainer.py
tests/version.txt

[model] add llama4

---

src/llamafactory/train/dpo/workflow.py
src/llamafactory/train/kto/workflow.py
src/llamafactory/train/pt/workflow.py
src/llamafactory/train/rm/workflow.py
src/llamafactory/train/sft/workflow.py

Fixing `"KeyError"` issue when dataset_module does not contain the `"eval_dataset"` key.
Changing `dataset_module["eval_dataset"]` to `dataset_module.get("eval_dataset")` can fix this, `dataset_module.get("eval_dataset")` will return `None` when dataset_module does not contain the `"eval_dataset"` key, but `dataset_module["eval_dataset"]` will lead to broken error like: 
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/rofunc/LLaMA-Factory/src/llamafactory/launcher.py", line 23, in <module>
[rank0]:     launch()
[rank0]:   File "/rofunc/LLaMA-Factory/src/llamafactory/launcher.py", line 19, in launch
[rank0]:     run_exp()
[rank0]:   File "/rofunc/LLaMA-Factory/src/llamafactory/train/tuner.py", line 107, in run_exp
[rank0]:     _training_function(config={"args": args, …
```

"KeyError" bug fix 

---

src/llamafactory/extras/misc.py

修复在Intel GPU上运行会显示未检测到CUDA环境

---

src/llamafactory/model/model_utils/liger_kernel.py

- The `enable_liger_kernel` function for the Gemma model series was not executed due to the existing `if` statement in the code.
- Changed the line to an `elif` statement so that the `apply_liger_kernel` function is executed properly.
Fixes #7628

fix: enable_gemma_liger_kernel

---

examples/train_lora/llama3_lora_sft_ray.yaml
src/llamafactory/hparams/training_args.py
src/llamafactory/train/trainer_utils.py

Fixes #7598 
Allows the user to specify kwargs for calling ray.init - for example:
```yaml
...
ray_init_kwargs:
runtime_env:
env_vars:
<YOUR-ENV-VAR-HERE>: "<YOUR-ENV-VAR-HERE>"
pip:
- emoji
...
```

Allow for specifying ray.init kwargs (i.e. runtime_env)

---

README.md
README_zh.md
src/llamafactory/extras/constants.py

框架可以直接支持即将发布的`GLM-4-0414` 模型（不考虑数据构建情况）
+ `chat_template` 不使用 Function Call 和 思维链方式和框架中`glm4`类相同。
+  需要在`src/llamafactory/extras/misc.py`支持`transformers`当前主分支（或者下一个版本）才能支持该模型，否则`transformers`无法读取到`GLM4`类。
例如:
```
check_version("transformers>=4.41.2,<=4.52.0dev,!=4.46.0,!=4.46.1,!=4.46.2,!=4.46.3,!=4.47.0,!=4.47.1,!=4.48.0")
```

支持 GLM-4-0414 模型

---

src/llamafactory/data/mm_plugin.py
src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/model/model_utils/moe.py
src/llamafactory/model/patcher.py

add kimi_vl
Fixes #7680  (issue)
1. Single GPU lora Finetuning ~50GB VRAM
2. Full Finetuning with zero2 @chenllliang
3. Multiple GPUs inference in webui w/o thinking
4. Failed in Multiple GPUs lora Finetuning
**lora**
```yaml
model_name_or_path: moonshotai/Kimi-VL-A3B-Instruct
trust_remote_code: true
stage: sft
do_train: true
lora_rank: 8
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj # ref deepseek ft
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
flash_attn: auto
dataset: identity, mllm_demo
template: kimi_vl
preprocessing_num_workers: 1
dataloader_num_workers: 4
output_dir: saves/kimi-vl/lora/
logging_steps: 1 …
```

[model] Support Kimi_VL thinking/instruct

---

src/llamafactory/model/adapter.py
src/llamafactory/webui/control.py

Fixes #7688
Issues where `QuantizationMethod.BITS_AND_BYTES` was used instead of  `QuantizationMethod.BNB`, updated to fix this.

Fixing QuantizationMethod.BITS_AND_BYTES to QuantizationMethod.BNB

---

src/llamafactory/model/model_utils/quantization.py

fix Gemma export
Fixes # 
[INFO|configuration_utils.py:1095] 2025-04-20 23:52:16,965 >> loading configuration file google/gemma-3-4b-it\generation_config.json 
[INFO|configuration_utils.py:1142] 2025-04-20 23:52:16,965 >> Generate config GenerationConfig {
"bos_token_id": 2,
"cache_implementation": "hybrid",
"do_sample": true,
"eos_token_id": [
1,
106
],
"pad_token_id": 0,
"top_k": 64,
"top_p": 0.95
}
Traceback (most recent call last):
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 715, in process_events
response = await route_utils.call_process_api(
File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
output = await app.get_blocks().process_api(
File …

fix Gemma export

---

src/llamafactory/data/collator.py

in the `get_rope_index` of qwen2vl, it only considers the attention masks with value 1. 
https://github.com/huggingface/transformers/blob/dc06e7cecd5dc98681566e5201481b42583c4382/src/transformers/models/qwen2_5_vl/modeling_qwen2_5_vl.py#L1682
But if we use the neat packing, the attention mask looks like `[1, 1, 2, 2, 2, 0]`, which yields a wrong position id for the second sentence.
I think this is related to #5426

[data] Fix wrong position ids with packed attention masks

---

src/llamafactory/hparams/training_args.py
src/llamafactory/train/trainer_utils.py

Adds 
```
ray_storage_filesystem: Optional[Literal["s3", "gs", "gcs"]] = field(
default=None,
metadata={"help": "The storage filesystem to use. If None specified, local filesystem will be used."},
)
```
to ray arguments to allow for specifying remote filesystems for uploading checkpoints. This creates an fsspec filesystem object to pass into [ray train run config](https://docs.ray.io/en/latest/train/api/doc/ray.train.RunConfig.html). This assumes that credentials for accessing the remote storage are already setup in the environment
For example, to upload the checkpoint to google cloud storage
```yaml
ray_run_name: llama3_8b_sft_lora
ray_storage_path: <storage-bucket-path>
ray_storage_filesystem: gs # gcs also works here
```
and the run will be stored at …

[ray] Expose storage_filesystem in ray train runconfig to support uploading checkpoints to remote storage

---

src/llamafactory/train/pt/workflow.py

Fixes #8096 
- caused when using eval_on_each_data_set
- caused by: eval_loss & eval_{key}_loss
I tested offline with the following yaml:
```yaml
model_name_or_path: /mnt/public/data/lh/models/Qwen2.5-0.5B
report_to: wandb
stage: pt
do_train: true
finetuning_type: full
dataset_dir: /mnt/public/data/lh/xiaochen/workspace/dataflow_pt/dataset/
dataset: medical_guidelines
preprocessing_num_workers: 128
output_dir: ./saves/Qwen2.5-0.5B/train_pt_medical_Qwen2.5-0.5B_ds2_epochs_1_datasets_old10b_wgsm8k_try_separate
save_steps: 2000
overwrite_output_dir: true
deepspeed: /mnt/public/data/lh/xiaochen/workspace/LLaMA-Factory/examples/deepspeed/ds_z2_config.json
per_device_train_batch_size: 8
gradient_accumulation_steps: 4 …
```

[workflow] fix KeyError at end of pretrain.

---

src/llamafactory/data/mm_plugin.py

Avoid errors when using image datasets with base64 type. 
Most text-image datasets on the Hugging Face dataset hub are in this format.
Thanks to @BUAADreamer

[data] fix internvl template when load base64 images

---

src/llamafactory/data/data_utils.py

Fixes #8182
To ensure the ```fs.isdir(cloud_path)``` is working with a valid fs, the fs from ```setup_fs(...)``` should be initialized properly before returning.

[data] Reading files from cloud is broken (#8182)

---

data/dataset_info.json

In the `lmsys/lmsys-chat-1m` dataset, the `user_tag` is defined as `user`. Naming it to `human` will cause `llamafactory.data.converter` to treat those entries as invalid and skip them.

Fix incorrect user_tag in dataset_info.json to prevent skipped entries

---

src/llamafactory/data/template.py
src/llamafactory/extras/constants.py

This PR adds support for the SmolLM2 model series by registering a new template ("smollm2") and model group, incorporating six model variants: SmolLM2-135M, SmolLM2-135M-Instruct, SmolLM2-360M, SmolLM2-360M-Instruct, SmolLM2-1.7B and SmolLM2-1.7B-Instruct.
Templates for Smollm and Smolm2 are different

feat: add smollm2 support

---

src/llamafactory/model/adapter.py
src/llamafactory/model/model_utils/unsloth.py

Fixes #8419. finetuning_args is missing as a parameter when resuming from checkpoint in unsloth

Fixes #8419: unsloth resume from checkpoint bug

---

src/llamafactory/hparams/parser.py

Fixes #7793
Enabled automatic type casting (e.g., 5e-5 → float) using OmegaConf
- As-Is: learning_rate:5e-5 → str
- To-Be: learning_rate:5e-5 → float
---
- As-Is: 
```
llamafactory-cli train examples/train_lora/llama3_lora_sft.yaml
```
```
[INFO|trainer.py:756] 2025-07-01 08:26:50,461 >> Using auto half precision backend
Traceback (most recent call last):
File "/home/name/anaconda3/bin/llamafactory-cli", line 8, in <module>
sys.exit(main())
^^^^^^
File "/home/name/LLaMA-Factory/src/llamafactory/cli.py", line 151, in main
COMMAND_MAP[command]()
File "/home/name/LLaMA-Factory/src/llamafactory/train/tuner.py", line 110, in run_exp
_training_function(config={"args": args, "callbacks": callbacks})
File "/home/name/LLaMA-Factory/src/llamafactory/train/tuner.py", line 72, in _training_function …
```

[parser] update config loading to use OmegaConf #7793

---

src/llamafactory/model/model_utils/unsloth.py

This PR reverts #8548. 
The requested feature in #8518 already [exists](https://github.com/hiyouga/LLaMA-Factory/blob/main/src/llamafactory/model/adapter.py#L230) and is correctly passed to `FastLanguageModel.get_peft_model`, instead of `FastLanguageModel.from_pretrained`.
Apologies for not noticing this earlier and for all the confusion -- I was searching for this arg in the wrong place. I hope we're able to merge this quickly so others do not face issues!

Revert "[model] add lora dropout to unsloth (#8548)" - requested feature already exists

---

docker/docker-cuda/README.md

Fixes #5387
Added comprehensive Linux-specific documentation for setting up Docker with NVIDIA GPU support. The issue reporter noted that `nvidia-container-toolkit` is required but not documented, which causes the Docker container to fail when trying to use GPUs.
- Created `docker/docker-cuda/README.md` with detailed setup instructions
- Documented installation steps for Docker, Docker Compose, and nvidia-container-toolkit
- Added GPU verification steps to ensure proper setup
- Included troubleshooting section for common issues
Without `nvidia-container-toolkit`, users on Linux cannot access their NVIDIA GPUs from within Docker containers. This documentation helps users avoid a common setup pitfall that's not immediately obvious.
The instructions provided are based on the official NVIDIA …

docs: add nvidia-container-toolkit to Linux Docker setup instructions

---

src/llamafactory/model/model_utils/embedding.py

During fine-tuning of **Qwen-2.5-VL**, several new special tokens are appended to the tokenizer.
After `model.resize_token_embeddings()`, `self.config.vocab_size` still keeps the original value **151 936**.  When computing `loss = criterion(logits, labels, vocab_size=self.config.vocab_size)` the last dimension of logits mismatches vocab_size and triggers a shape error.
Reproduced the shape-mismatch error on 1×A800; training proceeds normally after the fix.
```
[rank3]: Traceback (most recent call last):
[rank3]:   File "LLaMA-Factory/src/llamafactory/launcher.py", line 23, in <module>
[rank3]:     launch()
[rank3]:   File "LLaMA-Factory/src/llamafactory/launcher.py", line 19, in launch
[rank3]:     run_exp()
[rank3]:   File "LLaMA-Factory/src/llamafactory/train/tuner.py", line 110, in …
```

fix(embedding): adjust logits size after adding special tokens

---

.github/workflows/tests.yml
README.md
README_zh.md
examples/train_lora/gpt_lora_sft.yaml
requirements.txt
src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/extras/misc.py
src/llamafactory/model/loader.py
tests/version.txt

```bash
git clone --depth 1 https://github.com/hiyouga/LLaMA-Factory.git
cd LLaMA-Factory
pip install -e ".[torch,metrics]" --no-build-isolation
pip install "transformers==4.55.0"
```
```bash
llamafactory-cli train examples/train_lora/gpt_lora_sft.yaml
```
```bash
llamafactory-cli export --model_name_or_path openai/gpt-oss-20b --adapter_name_or_path saves/gpt-20b/lora/sft --export_dir gpt_merged
```
```bash
llamafactory-cli chat --model_name_or_path gpt_merged --template gpt
```

[model] add gpt oss

---

src/llamafactory/data/parser.py
src/llamafactory/hparams/data_args.py

Currently, `dataset_dir` must be either a string pointing to a local folder, an `ONLINE` keyword (for Hugging Face Hub), or a remote path starting with `REMOTE:`.
However, in some use cases — such as dynamic programmatic configuration or avoiding file I/O — it is desirable to pass a pre-parsed `dict` (i.e., already-loaded dataset_info) directly.
This PR enables that by allowing `dataset_dir` to be a `dict` as well.
- Check if `dataset_dir` is a `dict`, and if so, use it directly as `dataset_info`.
- Keeps backward compatibility for string-based usage (`ONLINE`, local path, and `REMOTE:` cases).
This improves flexibility and allows advanced users (e.g., internal toolchains or auto-generated dataset configs) to use `dataset_dir` as a native dict, without needing intermediate JSON files or …

[data-loader] Allow `dataset_dir` to accept a dict for in-memory dataset_info

---

src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/model/model_utils/moe.py
src/llamafactory/model/model_utils/visual.py

support glm45v model & update constants
_gpu peak memory:[45GB✖️8GPUS]_
```yaml
model_name_or_path: zai-org/GLM-4.5V
trust_remote_code: true
stage: sft
do_train: true
lora_rank: 8
deepspeed: examples/deepspeed/ds_z3_config.json
dataset: mllm_demo,identity,alpaca_en_demo
template: glm45v
preprocessing_num_workers: 16
dataloader_num_workers: 4
output_dir: saves/glm45v/lora/sft
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1 …
```

[model] support GLM4.5V

---

README.md
README_zh.md
src/llamafactory/data/template.py
src/llamafactory/extras/constants.py
src/llamafactory/model/model_utils/visual.py

Support Intern-s1-mini Model.
hf link: https://huggingface.co/internlm/Intern-S1-mini
modelscope link: https://modelscope.cn/models/Shanghai_AI_Laboratory/Intern-S1-mini/
Create a new file `examples/train_full/interns1_mini_lora_sft.yaml` with the following content:
```yaml
model_name_or_path:  internlm/Intern-S1-mini
trust_remote_code: true
stage: sft
do_train: true
freeze_vision_tower: true
freeze_multi_modal_projector: true
freeze_language_model: false
lora_rank: 8
dataset: mllm_demo,identity,alpaca_en_demo
template: intern_s1
preprocessing_num_workers: 16
dataloader_num_workers: 4
output_dir: saves/interns1_mini/full/sft …
```

[model] Support Intern-S1-mini
